import { BlurFade } from "@/components/ui/blur-fade";
import {useState,useRef,type KeyboardEvent} from 'react';
import {ArrowUpRight,HeartPulse,Code2,Palette,Leaf,BriefcaseBusiness,UsersRound,BookOpen,ArrowRight} from 'lucide-react';
const areas=[
 {name:'Salud y bienestar',icon:HeartPulse,color:'teal',question:'¿Te interesa comprender y cuidar a las personas?',text:'Explora cómo se estudia el cuerpo, la salud y el bienestar. Cada carrera combina de manera distinta ciencia, práctica y contacto humano.',careers:['Medicina','Enfermería','Nutrición'],compare:'Compara las prácticas clínicas, las materias científicas y el tipo de atención que te gustaría brindar.'},
 {name:'Tecnología e ingeniería',icon:Code2,color:'purple',question:'¿Disfrutas resolver problemas y construir soluciones?',text:'Desde desarrollar software hasta diseñar sistemas físicos: investiga qué problemas aborda cada disciplina y cómo se aprende a resolverlos.',careers:['Software','Ingeniería civil','Electrónica'],compare:'Revisa el peso de matemáticas, programación, laboratorios y proyectos en cada malla.'},
 {name:'Arte y comunicación',icon:Palette,color:'rose',question:'¿Te mueve crear y compartir nuevas ideas?',text:'La creatividad toma distintas formas: imágenes, espacios, historias y experiencias. Explora los procesos y las herramientas de cada campo.',careers:['Diseño gráfico','Comunicación','Artes visuales'],compare:'Investiga el trabajo de taller, los proyectos de portafolio y los medios con los que te gustaría trabajar.'},
 {name:'Ambiente y ciencias',icon:Leaf,color:'teal',question:'¿Te preguntas cómo funciona el mundo que te rodea?',text:'La observación, la investigación y el trabajo de campo abren caminos para comprender la naturaleza y sus desafíos.',careers:['Biología','Ingeniería ambiental','Agronomía'],compare:'Compara el trabajo en laboratorio, las salidas de campo y el enfoque de investigación.'},
 {name:'Negocios y organización',icon:BriefcaseBusiness,color:'amber',question:'¿Te interesa organizar proyectos y tomar decisiones?',text:'Conoce cómo se gestionan recursos, se analizan mercados y se desarrollan organizaciones. Explora la diferencia entre dirigir, investigar y emprender.',careers:['Administración','Economía','Contabilidad'],compare:'Revisa las materias de análisis cuantitativo, gestión, finanzas y proyectos aplicados.'},
 {name:'Sociedad y educación',icon:UsersRound,color:'purple',question:'¿Quieres comprender y acompañar a otras personas?',text:'Investiga cómo aprendemos, convivimos y construimos comunidad. Las posibilidades incluyen enseñanza, intervención social y análisis de nuestra realidad.',careers:['Educación','Trabajo social','Sociología'],compare:'Explora la práctica comunitaria, los métodos de investigación y los espacios donde se ejerce cada profesión.'},
];
export function StudyExplorer(){const[index,setIndex]=useState(0),buttons=useRef<(HTMLButtonElement|null)[]>([]),area=areas[index];function keyboard(e:KeyboardEvent,i:number){const next=e.key==='ArrowRight'?(i+1)%areas.length:e.key==='ArrowLeft'?(i+areas.length-1)%areas.length:e.key==='Home'?0:e.key==='End'?areas.length-1:null;if(next!==null){e.preventDefault();setIndex(next);buttons.current[next]?.focus();}}
return <section className="home-areas site-container" id="areas"><BlurFade className="home-section-top" inView><div><p className="site-eyebrow">ABRE EL MAPA DE POSIBILIDADES</p><h2>Hay más de un camino<br/>para lo que te interesa.</h2></div><p>Acércate a distintas áreas. No necesitas tener una respuesta para empezar a explorar.</p></BlurFade><BlurFade inView delay={0.07}><div className="home-area-tabs" role="tablist" aria-label="Áreas de estudio">{areas.map((a,i)=><button key={a.name} ref={el=>{buttons.current[i]=el;}} id={'area-tab-'+i} role="tab" aria-selected={index===i} aria-controls="area-panel" tabIndex={index===i?0:-1} onClick={()=>setIndex(i)} onKeyDown={e=>keyboard(e,i)}><a.icon size={20}/>{a.name}</button>)}</div></BlurFade><div id="area-panel" className={'home-area-panel '+area.color} role="tabpanel" aria-labelledby={'area-tab-'+index} tabIndex={0}><div className="home-area-main" key={area.name}><span className="home-area-icon"><area.icon size={30}/></span><h3>{area.question}</h3><p>{area.text}</p><div className="home-career-tags">{area.careers.map(c=><span key={c}>{c}<ArrowUpRight size={14}/></span>)}</div></div><aside><BookOpen size={23}/><h4>Una buena pregunta para comparar</h4><p>{area.compare}</p><a href="#estudiantes">Conoce las herramientas <ArrowRight size={16}/></a></aside></div><p className="home-area-note">Ejemplos de campos de estudio, no recomendaciones personales ni confirmación de oferta. Revisa la carrera y su disponibilidad con cada universidad.</p></section>;
}
