"use client";
import {useState} from 'react';
import {Upload} from 'lucide-react';
import {importSimulatorDocument} from '../../lib/import-simulator';
import {PagedList} from '../../components/ui/PagedList';
import {Button,Card,Field,PageHeader,SelectField,Notice,TextareaField} from '../../components/ui/primitives';
import {Dialog} from '../../components/ui/Dialog';
import {useTraining,trainingApi,TrainingError,decimal} from './shared';
import {SimulatorEditor,blankSimulator} from './TrainingEditors';
import {TrainingResult} from './SimulatorRun';
import './training.css';
export function AdminCourses(){
 const {data:d,error,busy,refresh,run}=useTraining();
 const [editing,setEditing]=useState<any>(null),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[career,setCareer]=useState(''),[deleting,setDeleting]=useState<any>(null);
 const [importOpen,setImportOpen]=useState(false),[importBusy,setImportBusy]=useState(false),[importError,setImportError]=useState(''),[importNotice,setImportNotice]=useState(''),[importMode,setImportMode]=useState<'file'|'html'>('file'),[html,setHtml]=useState('');
 const importDocument=async(file:File)=>{if(!d||importBusy)return;setImportBusy(true);setImportError('');try{const result=await importSimulatorDocument(file,blankSimulator(),d.careers);setEditing(result.simulator);setImportNotice(result.message);setImportOpen(false);setHtml('');}catch(e){setImportError((e as Error).message);}finally{setImportBusy(false);}};
 const perform=(fn:()=>Promise<any>)=>run(fn).catch(()=>{});
 const save=(publish=false)=>perform(async()=>{const e=await trainingApi('/entity',{kind:'simulator',entity:{...editing,status:publish?'published':'draft'}});setEditing(publish?null:e);});
 const list=(d?.simulators||[]).filter((s:any)=>s.title.toLocaleLowerCase().includes(query.toLocaleLowerCase())&&(!status||s.status===status)&&(!career||s.careerIds?.includes(career)));
 if(editing&&d)return <div className="training"><PageHeader title={editing.title||'Crear simulador'} description="Importa o crea preguntas, revisa sus claves y elige las carreras que recibirán la preparación." actions={<Button variant="secondary" disabled={busy} onClick={()=>perform(async()=>{await trainingApi('/entity',{kind:'simulator',entity:{...editing,status:'draft'}});setEditing(null);})}>Guardar y volver</Button>}/><TrainingError error={error} retry={refresh}/>{importNotice&&<Notice>{importNotice}</Notice>}<SimulatorEditor value={editing} onChange={setEditing} data={d}/><div className="training-actions simulator-save"><Button disabled={busy} variant="secondary" onClick={()=>save()}>Guardar borrador</Button><Button disabled={busy} onClick={()=>save(true)}>Validar y publicar</Button><Button variant="ghost" disabled={busy} onClick={()=>setEditing(null)}>Salir sin guardar</Button></div><p className="small muted">Publicar valida claves, explicación, revisión y carreras. La nota se calcula automáticamente al entregar.</p></div>;
 return <div className="training"><PageHeader title="Simuladores y preguntas" description="Crea la autopreparación de cada carrera. Publica un simulador y aparecerá directamente a los estudiantes que tengan esa carrera en sus resultados." actions={<div className="row"><Button variant="secondary" icon={<Upload size={17}/>} disabled={!d} onClick={()=>{setImportOpen(true);setImportError('');}}>Importar documento</Button><Button disabled={!d} onClick={()=>{setImportNotice('');setEditing(blankSimulator());}}>Crear simulador</Button></div>}/><TrainingError error={error} retry={refresh}/>{!d&&!error&&<p role="status">Cargando simuladores…</p>}{d&&<>
 <div className="training-summary"><div><strong>{d.simulators.filter((s:any)=>s.status==='published').length}</strong><p>Simuladores publicados</p></div><div><strong>{new Set(d.simulators.filter((s:any)=>s.status==='published').flatMap((s:any)=>s.careerIds||[])).size}</strong><p>Carreras con preparación</p></div><div><strong>{d.attempts.filter((a:any)=>a.state==='graded').length}</strong><p>Intentos calificados</p></div></div>
 <div className="training-toolbar"><Field label="Buscar simulador" type="search" value={query} onChange={e=>setQuery(e.target.value)}/><SelectField label="Estado" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos los estados</option><option value="draft">Borradores</option><option value="published">Publicados</option><option value="archived">Archivados</option></SelectField><SelectField label="Carrera" value={career} onChange={e=>setCareer(e.target.value)}><option value="">Todas las carreras asignadas</option>{d.careers.filter((c:any)=>d.simulators.some((s:any)=>s.careerIds?.includes(c.id))).map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</SelectField></div>
 {!d.simulators.length&&<div className="training-empty"><h2>Prepara tu primer simulador</h2><p>Importa PDF con texto, Word o HTML, o escribe las preguntas. Revisa la clave automática y asigna una o varias carreras.</p></div>}
 <PagedList className="training-grid" label="simuladores" resetKey={query+status+career}>{list.map((s:any)=><Card key={s.id+':'+s.version}><small>{s.status==='published'?'Publicado':s.status==='draft'?'Borrador':'Archivado'} · Versión {s.version}</small><h2>{s.title}</h2><p>{s.questionCount} preguntas · {s.durationMinutes} minutos de examen</p><p>{(s.careerIds||[]).map((id:string)=>d.careers.find((c:any)=>c.id===id)?.name).filter(Boolean).join(' · ')||'Selecciona carreras antes de publicar'}</p><div className="training-actions">{s.status==='draft'?<><Button onClick={()=>setEditing(structuredClone(s))}>Editar borrador</Button><Button variant="ghost" onClick={()=>setDeleting(s)}>Eliminar borrador</Button></>:<><Button variant="secondary" onClick={()=>setEditing({...structuredClone(s),version:0,revision:0,status:'draft'})}>Crear nueva versión</Button>{s.status==='published'&&<Button variant="ghost" onClick={()=>perform(()=>trainingApi('/archive',{kind:'simulator',id:s.id,version:s.version}))}>Archivar</Button>}</>}</div></Card>)}</PagedList>
 <details className="simulator-history"><summary>Progreso y notas de estudiantes · {d.attempts.length} intentos</summary><PagedList className="stack" label="intentos">{d.attempts.map((a:any)=><details key={a.id}><summary>{a.name} · {a.instrument.title} · {a.result?.percent!=null?decimal(a.result.percent)+' / 100':'En progreso'}</summary>{a.result?<TrainingResult attempt={a}/>:<p>El estudiante continúa su preparación.</p>}</details>)}</PagedList></details>
 </>}<Dialog open={importOpen} title="Importar simulador desde un documento" onClose={()=>{if(!importBusy)setImportOpen(false);}} wide><div className="stack"><p className="muted">Carga Word (.docx), PDF con texto o HTML, hasta 10 MB. Después revisa preguntas, claves, puntajes, tiempo y carreras antes de publicar.</p><div className="row"><Button variant={importMode==='file'?'primary':'secondary'} disabled={importBusy} onClick={()=>setImportMode('file')}>Subir archivo</Button><Button variant={importMode==='html'?'primary':'secondary'} disabled={importBusy} onClick={()=>setImportMode('html')}>Pegar código HTML</Button></div>{importMode==='file'?<label className="simulator-import-file">Selecciona tu documento<span className="button button--secondary">Seleccionar archivo</span><input className="sr-only" aria-label="Seleccionar documento del simulador" type="file" accept=".docx,.pdf,.html,.htm" disabled={importBusy} onChange={e=>{const file=e.target.files?.[0];if(file)void importDocument(file);e.target.value='';}}/></label>:<><TextareaField label="Código HTML del simulador" rows={8} value={html} disabled={importBusy} onChange={e=>setHtml(e.target.value)}/><Button loading={importBusy} disabled={!html.trim()} onClick={()=>void importDocument(new File([html],'simulador.html',{type:'text/html'}))}>Importar HTML</Button></>}{importBusy&&<p role="status">Preparando preguntas e introducción…</p>}{importError&&<Notice tone="danger">{importError}</Notice>}</div></Dialog><Dialog open={!!deleting} title="Eliminar borrador" onClose={()=>setDeleting(null)}><p>Se eliminará {deleting?.title}. Los intentos anteriores se conservan.</p><Button disabled={busy} onClick={()=>perform(async()=>{await trainingApi('/delete-draft',{kind:'simulator',id:deleting.id,version:deleting.version});setDeleting(null);})}>Confirmar eliminación</Button></Dialog></div>;
}
