"use client";
import {TestPublication} from "../../components/domain/TestPublication";
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {PagedList} from '../../components/ui/PagedList';
import {Button,Card,Field,SelectField,PageHeader,Notice} from '../../components/ui/primitives';
import {useTraining,trainingApi,TrainingError,decimal} from './shared';
import {SimulatorRun,TrainingResult} from './SimulatorRun';
import {principalGrade} from '../../lib/training-engine';
import './training.css';
export function StudentCourses(){
 const {data:d,error,busy,refresh,run}=useTraining();
 const [career,setCareer]=useState(''),[query,setQuery]=useState(''),[active,setActive]=useState<any>(null),[result,setResult]=useState<any>(null);
 useEffect(()=>{if(!d)return;const id=new URLSearchParams(window.location.search).get('carrera');if(id&&d.recommendations.some((r:any)=>r.careerId===id))setCareer(id);},[d?.recommendations?.map((r:any)=>r.careerId).join(',')]);
 const [area,setArea]=useState(''),[state,setState]=useState(''),[historyQuery,setHistoryQuery]=useState('');
 const match=(text:string,q:string)=>text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(q.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase());
 const choose=(id:string)=>{setCareer(id);setQuery('');setState('');setArea('');window.history.replaceState(null,'',id?'?carrera='+encodeURIComponent(id):window.location.pathname);};
 const attempts=(id:string)=>(d?.attempts||[]).filter((a:any)=>a.simulator.id===id);
 const simulators=(id:string)=>(d?.simulators||[]).filter((s:any)=>s.careerIds?.includes(id));
 const complete=(s:any)=>attempts(s.id).some((a:any)=>a.state==='graded');
 const selected=d?.careers.find((c:any)=>c.id===career);
 if(active)return <div className="training"><SimulatorRun initial={active} onClose={()=>{setActive(null);void refresh();}}/></div>;
 if(result)return <div className="training"><Button variant="secondary" onClick={()=>setResult(null)}>Volver a mis simuladores</Button><TrainingResult attempt={result}/></div>;
 return <div className="training"><PageHeader title={selected?'Autopreparación para '+selected.name:'Tu autopreparación'} description={selected?'Practica con los simuladores de esta carrera. Obtén tu nota al entregar y consulta tus avances.':'Elige una de las carreras recomendadas por tus tests para comenzar a practicar.'}/><TestPublication/><TrainingError error={error} retry={refresh}/>{!d&&!error&&<p role="status">Cargando tu preparación…</p>}{d&&<>
 {selected?<><Button variant="secondary" onClick={()=>choose('')}>Volver a mis carreras</Button><div className="training-summary"><div><strong>{simulators(career).length}</strong><p>Simuladores disponibles</p></div><div><strong>{simulators(career).filter(complete).length}</strong><p>Simuladores completados</p></div><div><strong>{simulators(career).length?Math.round(simulators(career).filter(complete).length/simulators(career).length*100):0}%</strong><p>Progreso de preparación</p></div></div><div className="preparation-filters"><Field label="Buscar simulador" type="search" value={query} onChange={e=>setQuery(e.target.value)}/><SelectField label="Estado de preparación" value={state} onChange={e=>setState(e.target.value)}><option value="">Todos los estados</option><option value="pending">Sin comenzar</option><option value="progress">En curso</option><option value="done">Completado</option></SelectField></div>
 {!simulators(career).length&&<Notice>La preparación de esta carrera aún no tiene simuladores publicados. Aparecerán aquí cuando administración los publique.</Notice>}
 <PagedList className="training-grid" label="simuladores" resetKey={career+query+state}>{simulators(career).filter((s:any)=>match(s.title,query)&&(!state||(state==='done'?complete(s):state==='progress'?attempts(s.id).some((a:any)=>a.state==='in_progress'):!attempts(s.id).length))).map((s:any)=>{const rows=attempts(s.id),graded=rows.filter((a:any)=>a.result?.percent!=null);return <Card key={s.id}><small>Autocalificable · Versión {s.version}</small><h2>{s.title}</h2><p>{s.instrument.description}</p><p>{s.questionCount} preguntas · Examen: {s.durationMinutes} minutos</p>{s.modes.map((mode:string)=>{const history=rows.filter((a:any)=>a.mode===mode),open=history.find((a:any)=>a.state==='in_progress'),scores=history.filter((a:any)=>a.result?.percent!=null).map((a:any)=>a.result.percent);return <div className="simulator-mode" key={mode}><div><b>{mode==='exam'?'Examen cronometrado':'Práctica'}</b><p>{scores.length?'Nota: '+decimal(principalGrade(scores,s.gradePolicy))+' / 100':'Todavía sin nota'} · {history.length} / {s.maxAttempts} intentos</p></div><Button disabled={busy||!open&&history.length>=s.maxAttempts} onClick={()=>run(async()=>setActive(await trainingApi('/simulator/start',{simulatorId:s.id,mode}))).catch(()=>{})}>{open?'Continuar':mode==='exam'?'Iniciar examen':'Practicar'}</Button></div>;})}{graded.length>0&&<details><summary>Mis notas y respuestas · {graded.length} entregas</summary>{[...graded].reverse().map((a:any)=><div className="simulator-grade" key={a.id}><span>{a.mode==='exam'?'Examen':'Práctica'} · {new Date(a.finished_at).toLocaleDateString('es-EC')} · <b>{decimal(a.result.percent)} / 100</b></span><Button variant="ghost" onClick={()=>setResult(a)}>Ver resultado</Button></div>)}</details>}</Card>;})}</PagedList></>:<>
 {!d.recommendations.length?<Card><h2>Primero conoce tus carreras recomendadas</h2><p>Completa tus tests para recibir una ruta de autopreparación acorde a tus resultados.</p><Link className="button button--primary" href="/mi-ruta/evaluaciones">Ir a mis tests</Link></Card>:<><div className="preparation-filters"><Field label="Buscar carrera recomendada" type="search" value={query} onChange={e=>setQuery(e.target.value)}/><SelectField label="Área de estudio" value={area} onChange={e=>setArea(e.target.value)}><option value="">Todas las áreas</option>{Array.from(new Set<string>(d.careers.map((c:any)=>c.area))).sort().map(a=><option key={a}>{a}</option>)}</SelectField><SelectField label="Disponibilidad" value={state} onChange={e=>setState(e.target.value)}><option value="">Todas mis carreras</option><option value="available">Con simuladores</option><option value="done">Con avances</option><option value="empty">Sin simuladores aún</option></SelectField></div><PagedList className="training-grid preparation-careers" label="carreras recomendadas" resetKey={query+area+state}>{d.recommendations.filter((r:any)=>{const c=d.careers.find((c:any)=>c.id===r.careerId);return c&&match(c.name,query)&&(!area||c.area===area)&&(!state||(state==='available'?simulators(c.id).length>0:state==='done'?simulators(c.id).some(complete):!simulators(c.id).length));}).map((r:any)=>{const c=d.careers.find((c:any)=>c.id===r.careerId);if(!c)return null;const list=simulators(c.id),done=list.filter(complete).length;return <Card key={c.id}><small>Carrera recomendada · {c.area}</small><h2>{c.name}</h2><details className="career-reason"><summary>Por qué aparece esta carrera</summary><p>{r.reason}</p></details><p>{list.length} simuladores disponibles · {done} completados</p><progress aria-label={'Progreso en '+c.name} max={Math.max(1,list.length)} value={done}/><Button onClick={()=>choose(c.id)}>Autopreparación</Button></Card>;})}</PagedList></>}
 </>}
 <details className="simulator-history"><summary>Historial de notas · {d.attempts.filter((a:any)=>a.result).length} entregas</summary><Field label="Buscar en mis notas" type="search" value={historyQuery} onChange={e=>setHistoryQuery(e.target.value)}/><PagedList className="stack" label="resultados" resetKey={historyQuery}>{d.attempts.filter((a:any)=>a.result&&match(a.instrument.title,historyQuery)).map((a:any)=><div className="simulator-grade" key={a.id}><span>{a.instrument.title} · {a.result.percent!=null?decimal(a.result.percent)+' / 100':'Pendiente'}</span><Button variant="secondary" onClick={()=>setResult(a)}>Ver resultado</Button></div>)}</PagedList></details>
 </>}</div>;
}
