import {readDocumentMarkup} from '../../components/kit/lib/import-content.ts';
export {proposeTests} from '../../components/kit/lib/import-content.ts';
import { parseHTML } from 'linkedom';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
function fail(message:string):never{throw new Error(message);}
export async function extractFile(bytes:Buffer,name:string,onProgress:(value:number)=>void=()=>{}){let text='',embedded:any[]=[];const warnings:string[]=[];const images:{src:string;alt:string;source:string}[]=[];const extension=name.split('.').pop()?.toLowerCase();
if(extension==='html'||extension==='htm'){if(!/<(?:!doctype|html|body|p|div|form|fieldset|ol|ul|table|script|h[1-6])(?:\s|>)/i.test(bytes.toString('utf8')))fail('El archivo no contiene HTML reconocible.');const html=bytes.toString('utf8');const {document}=parseHTML(/<html[\s>]/i.test(html)?html:'<html><body>'+html+'</body></html>');const parsed=readDocumentMarkup(document);text=parsed.text;embedded=parsed.embedded;warnings.push(...parsed.warnings);
}else if(extension==='docx'){if(bytes.length<4||bytes.readUInt32LE(0)!==0x04034b50)fail('El archivo no es un documento DOCX válido.');let end=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(bytes.readUInt32LE(i)===0x06054b50){end=i;break;}if(end<0)fail('El DOCX está incompleto.');const entries=bytes.readUInt16LE(end+10);let cursor=bytes.readUInt32LE(end+16),expanded=0;if(entries>1000)fail('El documento contiene demasiados archivos internos.');for(let i=0;i<entries;i++){if(cursor+46>bytes.length||bytes.readUInt32LE(cursor)!==0x02014b50)fail('La estructura DOCX no es válida.');expanded+=bytes.readUInt32LE(cursor+24);if(expanded>50000000)fail('El documento descomprimido excede el límite permitido.');cursor+=46+bytes.readUInt16LE(cursor+28)+bytes.readUInt16LE(cursor+30)+bytes.readUInt16LE(cursor+32);}const mammoth=await import('mammoth');const converted=await mammoth.convertToHtml({buffer:bytes},{convertImage:mammoth.images.imgElement(async image=>{const data=await image.read('base64');if(!['image/png','image/jpeg','image/webp'].includes(image.contentType)||data.length>333336||images.length>=8){warnings.push('Una imagen de Word requiere revisión en el documento original por tamaño o formato.');return {src:'',alt:'Imagen disponible en el documento original'};}const src='data:'+image.contentType+';base64,'+data;images.push({src,alt:'',source:'Word · imagen '+(images.length+1)});return {src};})});const {document}=parseHTML('<html><body>'+converted.value+'</body></html>');const parsed=readDocumentMarkup(document);text=parsed.text;embedded=parsed.embedded;warnings.push(...parsed.warnings);if(images.length)warnings.push('Revisa las '+images.length+' imágenes extraídas de Word y asígnalas a sus preguntas desde el editor. No se asociaron automáticamente.');if(converted.messages.length)warnings.push('Word contiene elementos de formato que requieren contraste con el original.');
}else if(extension==='pdf'){if(bytes.subarray(0,5).toString()!=='%PDF-')fail('El archivo no es un PDF válido.');const canvas=await import('@napi-rs/canvas');Object.assign(globalThis,{DOMMatrix:canvas.DOMMatrix,ImageData:canvas.ImageData,Path2D:canvas.Path2D});const pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc=pathToFileURL(resolve('node_modules/pdfjs-dist/legacy/build/pdf.worker.mjs')).href;const loading=pdfjs.getDocument({data:new Uint8Array(bytes),useSystemFonts:true});let worker:any;try{const pdf=await loading.promise;if(pdf.numPages>60)fail('Importa documentos de hasta 60 páginas.');for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i),content=await page.getTextContent();let pageText=content.items.map((item:any)=>item.str+(item.hasEOL?'\n':' ')).join('');if(pageText.trim().length<20){const viewport=page.getViewport({scale:1.5});if(viewport.width>10000||viewport.height>10000||viewport.width*viewport.height>20000000)fail('La página escaneada excede el tamaño permitido. Reduce su resolución antes de importar.');if(!worker){const tesseract=await import('tesseract.js');worker=await tesseract.createWorker('spa+eng');}const surface=canvas.createCanvas(Math.ceil(viewport.width),Math.ceil(viewport.height));await page.render({canvasContext:surface.getContext('2d') as any,canvas:surface as any,viewport}).promise;const recognized=(await worker.recognize(surface.toBuffer('image/png'))).data;pageText=recognized.text;warnings.push('Página '+i+': texto obtenido mediante OCR. Revisa caracteres, opciones y numeración en el original (confianza de lectura: '+Math.round(recognized.confidence)+'%).');}text+='\n[Página '+i+']\n'+pageText;onProgress(10+Math.round(i/pdf.numPages*85));}}catch(error:any){if(error?.name==='PasswordException')fail('El PDF está protegido por contraseña. Sube una copia sin cifrado.');throw error;}finally{if(worker)await worker.terminate();await loading.destroy();}
}else fail('Selecciona un archivo PDF, Word (.docx) o HTML. Los documentos .doc deben convertirse a .docx.');
if(text.length>1000000)fail('El documento contiene demasiado texto. Divídelo en archivos más pequeños.');return {text,embedded,warnings,images};}
