import {validateDraft,instrumentFor,battery} from './battery';
import { contentProblem } from '@/components/kit/lib/content-fields';
import { labSettingsProblem } from '@/components/kit/data/lab-settings';
import { randomUUID,randomBytes } from 'node:crypto';
import { instruments, dimensionScores, answerKey } from '@/components/kit/data/instruments';
import { db,fail,document,put,shared,assigned,validateTest,passwordHash } from './store';
export function saveDocument(user:any,key:string,value:any,revision?:number){if(!key.startsWith('rv360:')||key.length>160||JSON.stringify(value).length>1500000)fail('Datos no válidos.');if(['rv360:adult','rv360:submissions','rv360:versions','rv360:audit','rv360:published-content','rv360:imports','rv360:battery','rv360:email-change','rv360:profile'].includes(key))fail('Este registro solo puede modificarse mediante su operación autorizada.',403);if(key.startsWith('rv360:answers:')){if(user.role!=='student')fail('Solo estudiantes pueden responder.',403);validateDraft(user,key,value);}const isShared=shared(key);if(isShared&&user.role!=='admin')fail('Solo administración puede modificar este apartado.',403);const owner=isShared?'institution:'+user.institutionId:user.id;const old=db.prepare('SELECT revision FROM documents WHERE owner=? AND key=?').get(owner,key) as any;if(revision!==undefined&&(old?.revision||0)!==revision)fail('Este apartado cambió en otra sesión. Recarga para revisar la versión actual.',409);
 if(key==='rv360:admin-content'){const problem=contentProblem(value);if(problem)fail(problem);}
 if(key==='rv360:admin-lab-settings'){const problem=labSettingsProblem(value);if(problem)fail(problem);}
 if(key==='rv360:custom-tests'){if(!Array.isArray(value))fail('Catálogo no válido.');const previous=document(owner,key,[]);if(previous.some((p:any)=>(p.publishedAt||p.status==='Publicado')&&!value.some((t:any)=>t.id===p.id)))fail('Archiva las versiones publicadas; no se pueden eliminar.');for(const t of value){validateTest(t);const prior=previous.find((p:any)=>p.id===t.id);if((prior?.status==='Publicado'||prior?.publishedAt)&&JSON.stringify({...prior,status:'',publishedAt:''})!==JSON.stringify({...t,status:'',publishedAt:''}))fail('Una versión publicada es inmutable. Duplícala para crear una nueva versión.');if(prior?.publishedAt)t.publishedAt=prior.publishedAt;if(t.status==='Publicado'&&!t.publishedAt)t.publishedAt=new Date().toISOString();}}
 if(key==='rv360:admin-groups')fail('La gestión de grupos fue retirada.',410);
 if(key==='rv360:admin-users'){if(!Array.isArray(value))fail('Usuarios no válidos.');db.exec('BEGIN IMMEDIATE');try{for(const u of value){if(!u.name?.trim()||!/^\S+@\S+\.\S+$/.test(u.email)||!['Estudiante','Orientador'].includes(u.role)||!['Activo','Suspendido','Invitación pendiente'].includes(u.status))fail('Revisa los campos del usuario.');const existing=db.prepare('SELECT * FROM users WHERE id=?').get(u.id) as any;if(existing){if(existing.institutionId!==user.institutionId||existing.role==='admin')fail('No puedes modificar esta cuenta.',403);db.prepare('UPDATE users SET name=?,role=?,groupName=?,status=? WHERE id=?').run(u.name,u.role==='Estudiante'?'student':'orientador',u.group,u.status,u.id);}else{if(db.prepare('SELECT id FROM users WHERE email=?').get(u.email.toLowerCase()))fail('Ese correo ya está registrado.');db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,?,?)').run(u.id,u.name,u.email.toLowerCase(),passwordHash(randomBytes(32).toString('hex')),u.role==='Estudiante'?'student':'orientador',user.institutionId,u.group,'Invitación pendiente');}}db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}}
 if(key==='rv360:profile'){if(typeof value.name!=='string'||value.name.trim().length<3)fail('Escribe tu nombre completo.');value.email=user.email;db.prepare('UPDATE users SET name=? WHERE id=?').run(value.name.trim(),user.id);}
 if(key==='rv360:admin-settings'){const org=db.prepare('SELECT code FROM institutions WHERE id=?').get(user.institutionId) as any;value.code=org?.code||'';if(!value.name?.trim())fail('Escribe el nombre de la plataforma.');db.prepare('UPDATE institutions SET name=? WHERE id=?').run(value.name,user.institutionId);}
 put(owner,key,value);if(isShared)put(owner,'rv360:audit',[{name:user.name,action:'Actualizar',entity:key,created_at:new Date().toISOString()},...document(owner,'rv360:audit',[])].slice(0,1000));return (db.prepare('SELECT revision FROM documents WHERE owner=? AND key=?').get(owner,key) as any).revision;
}
export function submitAssessment(user:any,id:string){if(user.role!=='student')fail('Esta operación corresponde a estudiantes.',403);const custom=document('institution:'+user.institutionId,'rv360:custom-tests',[]);const instrument:any=instrumentFor(user,id);if(!instrument)fail('La evaluación no está asignada a tu cuenta.',403);if(instrument.availableFrom&&new Intl.DateTimeFormat('en-CA',{timeZone:document('institution:'+user.institutionId,'rv360:admin-settings',{}).timezone||'America/Guayaquil'}).format(new Date())<instrument.availableFrom)fail('Esta evaluación aún no está disponible.');if(instrument.due&&new Intl.DateTimeFormat('en-CA',{timeZone:document('institution:'+user.institutionId,'rv360:admin-settings',{}).timezone||'America/Guayaquil'}).format(new Date())>instrument.due)fail('El plazo de esta evaluación terminó.');const answers=document(user.id,answerKey(instrument),{});const serialized=JSON.stringify(answers);const prior=db.prepare('SELECT id FROM submissions WHERE user_id=? AND instrument_id=? AND version=? AND answers=?').get(user.id,id,instrument.version,serialized);if(prior)return prior;const count=(db.prepare('SELECT COUNT(*) n FROM submissions WHERE user_id=? AND instrument_id=? AND version=?').get(user.id,id,instrument.version) as any).n;if(instrument.maxAttempts&&count>=instrument.maxAttempts)fail('Alcanzaste el número de intentos permitidos.');const scores=evaluateInstrument(instrument,answers);const record={id:randomUUID(),user_id:user.id,instrument_id:id,version:instrument.version,answers:serialized,scores:JSON.stringify(scores),snapshot:JSON.stringify(instrument),created_at:new Date().toISOString()};db.prepare('INSERT INTO submissions VALUES(?,?,?,?,?,?,?,?)').run(...Object.values(record));return {id:record.id};}

export function evaluateInstrument(instrument:any,answers:Record<string,any>){
 const absent=(value:any)=>value===undefined||value===null||value===''||(Array.isArray(value)&&!value.length);
 const valid=instrument.questions.every((q:any)=>q.required===false&&absent(answers[q.id])|| (q.type==='open'?typeof answers[q.id]==='string'&&answers[q.id].trim():q.type==='multiple'?Array.isArray(answers[q.id])&&answers[q.id].length&&new Set(answers[q.id]).size===answers[q.id].length&&answers[q.id].every((v:any)=>(q.options||instrument.options).some((o:any)=>o.value===v)):(q.options||instrument.options).some((o:any)=>o.value===answers[q.id])));
 if(!valid)fail('Responde todas las preguntas obligatorias y revisa las opciones antes de finalizar.');
 const id=instrument.id;
 if(instruments.some(i=>i.id===id))return dimensionScores(instrument,answers).map(s=>({...s,raw:instrument.questions.filter((q:any)=>q.dimension===s.dimension).reduce((n:number,q:any)=>n+answers[q.id],0),percent:id==='autoconocimiento'?Math.round(s.value*20):undefined}));
 if(instrument.scoring==='manual'||!instrument.scoring)return [];
 const eligible=instrument.questions.filter((q:any)=>!absent(answers[q.id])&&(instrument.scoring==='objective'||!['open','multiple'].includes(q.type)));
 return [...new Set(eligible.map((q:any)=>q.dimension||'General'))].map(d=>{
  const qs=eligible.filter((q:any)=>(q.dimension||'General')===d);
  const raw=qs.reduce((n:number,q:any)=>{const v=answers[q.id],weight=q.weight||1;if(instrument.scoring==='objective'){const selected=Array.isArray(v)?v:[v];return n+(selected.length===q.correctValues.length&&selected.every((v:number)=>q.correctValues.includes(v))?weight:0);}const opts=q.options||instrument.options;return n+(q.inverse?Math.max(...opts.map((o:any)=>o.value))+Math.min(...opts.map((o:any)=>o.value))-v:v)*weight;},0);
  const value=raw/qs.reduce((n:number,q:any)=>n+(q.weight||1),0);
  const metric=instrument.aggregation==='sum'?raw:value;
  const band=instrument.ranges?.find((r:any)=>(!r.dimension||r.dimension===d)&&metric>=r.min&&metric<=r.max)?.label;
  return {dimension:d,value,raw,band};
 });
}
