import {batteryForClient} from './battery';
import { testProblem } from './test-validation';
import 'server-only';
import { DatabaseSync } from 'node:sqlite';
import { randomBytes, scryptSync, timingSafeEqual, createHash } from 'node:crypto';
import { mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { cookies } from 'next/headers';
const location=resolve(/*turbopackIgnore: true*/ process.env.DATABASE_PATH||'storage/ruta.sqlite');mkdirSync(dirname(location),{recursive:true});
const globalDB=globalThis as unknown as {rutaDB?:DatabaseSync};
export const db=globalDB.rutaDB||(globalDB.rutaDB=new DatabaseSync(location));
db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password TEXT NOT NULL,role TEXT NOT NULL,institutionId TEXT,groupName TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'Activo');
CREATE TABLE IF NOT EXISTS institutions(id TEXT PRIMARY KEY,name TEXT NOT NULL,code TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,userId TEXT NOT NULL REFERENCES users(id),expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS documents(owner TEXT NOT NULL,key TEXT NOT NULL,value TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1,PRIMARY KEY(owner,key));
CREATE TABLE IF NOT EXISTS submissions(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),instrument_id TEXT NOT NULL,version TEXT NOT NULL,answers TEXT NOT NULL,scores TEXT NOT NULL,snapshot TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS released_results(submission_id TEXT PRIMARY KEY REFERENCES submissions(id),released_by TEXT NOT NULL REFERENCES users(id),released_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS resets(token TEXT PRIMARY KEY,userId TEXT NOT NULL,expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS attempts(key TEXT PRIMARY KEY,count INTEGER NOT NULL,until INTEGER NOT NULL);
`);
export const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
export function passwordHash(password:string){const salt=randomBytes(16).toString('hex');return salt+':'+scryptSync(password,salt,64).toString('hex');}
export function passwordMatches(password:string,stored:string){const [salt,digest]=stored.split(':');if(!salt||!digest)return false;const expected=Buffer.from(digest,'hex');const actual=scryptSync(password,salt,64);return expected.length===actual.length&&timingSafeEqual(expected,actual);}
export function fail(message:string,status=400):never{throw Object.assign(new Error(message),{status});}
export function publicUser(row:any){return {id:row.id,name:row.name,email:row.email,role:row.role,institutionId:row.institutionId,group:row.groupName};}
export async function currentUser(){const token=(await cookies()).get('rv360_session')?.value;if(!token)return null;const row=db.prepare('SELECT u.* FROM sessions s JOIN users u ON u.id=s.userId WHERE s.token=? AND s.expires>? AND u.status=?').get(hash(token),Date.now(),'Activo');return row?publicUser(row):null;}
export async function requireUser(admin=false){const user=await currentUser();if(!user)fail('Inicia sesión para continuar.',401);if(admin&&user.role!=='admin')fail('No tienes permiso para esta operación.',403);return user;}
export async function createSession(id:string){const token=randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(hash(token),id,Date.now()+86400000);(await cookies()).set('rv360_session',token,{httpOnly:true,sameSite:'lax',secure:process.env.COOKIE_SECURE==='true'||process.env.APP_URL?.startsWith('https://')||false,path:'/',maxAge:86400});}
export async function closeSession(){const jar=await cookies();const token=jar.get('rv360_session')?.value;if(token)db.prepare('DELETE FROM sessions WHERE token=?').run(hash(token));jar.delete('rv360_session');}
export function rateLimit(key:string){const row=db.prepare('SELECT * FROM attempts WHERE key=?').get(key) as any;const now=Date.now();if(row&&row.until>now&&row.count>=12)fail('Demasiados intentos. Inténtalo en 15 minutos.',429);db.prepare('INSERT OR REPLACE INTO attempts VALUES(?,?,?)').run(key,row&&row.until>now?row.count+1:1,row&&row.until>now?row.until:now+900000);}
export function document(owner:string,key:string,fallback:any=null){const row=db.prepare('SELECT value FROM documents WHERE owner=? AND key=?').get(owner,key) as any;return row?JSON.parse(row.value):fallback;}
export function put(owner:string,key:string,value:any){db.prepare('INSERT INTO documents(owner,key,value) VALUES(?,?,?) ON CONFLICT(owner,key) DO UPDATE SET value=excluded.value,revision=revision+1').run(owner,key,JSON.stringify(value));}
export const shared=(key:string)=>key.startsWith('rv360:admin-')||['rv360:custom-tests','rv360:versions','rv360:published-content','rv360:audit'].includes(key);
export function platformInstitution(){const config=document('system','rv360:platform');const org=config?.institutionId?db.prepare('SELECT * FROM institutions WHERE id=?').get(config.institutionId) as any:null;if(!org)fail('La plataforma aún no tiene configurado el registro de usuarios.',503);return org;}
export function assigned(test:any,user:any){const platform=document('system','rv360:platform');return test.status==='Publicado'&&(!test.studentId||test.studentId===user.id)&&(user.institutionId===platform?.institutionId||test.group==='Todos los estudiantes'||test.group===user.group);}
export function workspace(user:any){if(!user)return {user:user||null,values:{},revisions:{},mailConfigured:!!process.env.SMTP_HOST};const values:Record<string,any>={},revisions:Record<string,number>={};for(const row of db.prepare('SELECT * FROM documents WHERE owner=? OR owner=?').all(user.id,'institution:'+user.institutionId) as any[]){if(row.owner!==user.id&&user.role!=='admin'&&!['rv360:custom-tests','rv360:published-content','rv360:admin-lab-settings'].includes(row.key))continue;if(['rv360:email-change','rv360:battery','rv360:adult'].includes(row.key))continue;values[row.key]=JSON.parse(row.value);revisions[row.key]=row.revision;}
 if(user.role!=='admin')values['rv360:custom-tests']=(values['rv360:custom-tests']||[]).filter((t:any)=>assigned(t,user)).map((t:any)=>{const today=new Intl.DateTimeFormat('en-CA',{timeZone:document('institution:'+user.institutionId,'rv360:admin-settings',{}).timezone||'America/Guayaquil'}).format(new Date());return {...studentInstrument(t),availability:t.availableFrom&&today<t.availableFrom?'future':t.due&&today>t.due?'closed':'open'};});
 values['rv360:profile']={name:user.name,email:user.email,stage:'',institution:'',reminders:'no',...values['rv360:profile']};
 if(user.role==='admin'){const institution=db.prepare('SELECT * FROM institutions WHERE id=?').get(user.institutionId) as any;values['rv360:admin-settings']={name:institution?.name||'',code:institution?.code||'',email:user.email,year:String(new Date().getFullYear()),timezone:'America/Guayaquil',selfRegistration:'yes',reviewRequired:'yes',...values['rv360:admin-settings']};}
 const people=user.role==='student'?[]:db.prepare('SELECT * FROM users WHERE institutionId=? AND role!=?').all(user.institutionId,'admin').filter((u:any)=>user.role==='admin'||u.groupName===user.group);
 values['rv360:admin-users']=people.map((u:any)=>({id:u.id,name:u.name,email:u.email,role:u.role==='student'?'Estudiante':'Orientador',group:u.groupName,status:u.status,stage:document(u.id,'rv360:profile',{}).stage||'',institution:document(u.id,'rv360:profile',{}).institution||''}));
 values['rv360:submissions']=db.prepare('SELECT s.* FROM submissions s JOIN users u ON s.user_id=u.id WHERE '+(user.role==='student'?'u.id=?':'u.institutionId=?'+(user.role==='orientador'?' AND u.groupName=?':''))+' ORDER BY s.created_at DESC').all(...(user.role==='student'?[user.id]:user.role==='orientador'?[user.institutionId,user.group]:[user.institutionId]));
 values['rv360:submissions']=values['rv360:submissions'].map((row:any)=>visibleSubmission(row,user));
 values['rv360:battery']=batteryForClient(user);
 return {user,values,revisions,mailConfigured:!!process.env.SMTP_HOST};}
export function validateTest(t:any){const problem=testProblem(t||{});if(problem)fail(problem);if(!t||typeof t.id!=='string'||!t.title?.trim()||!Array.isArray(t.questions)||!t.questions.length||t.questions.length>500)fail('El test necesita un título y entre 1 y 500 preguntas.');if(!['Borrador','Publicado','Archivado'].includes(t.status)||typeof t.version!=='string')fail('Estado o versión no válidos.');if(t.maxAttempts!==undefined&&(!Number.isInteger(t.maxAttempts)||t.maxAttempts<0||t.maxAttempts>20))fail('El número de intentos debe estar entre 0 y 20.');if(t.ranges&&(!Array.isArray(t.ranges)||t.ranges.length>50||t.ranges.some((r:any)=>!Number.isFinite(r.min)||!Number.isFinite(r.max)||r.min>r.max||!r.label?.trim())))fail('Revisa los límites y etiquetas de los rangos.');const ids=new Set();for(const q of t.questions){if(!q.id||ids.has(q.id)||!q.text?.trim())fail('Revisa los identificadores y textos de las preguntas.');ids.add(q.id);if(q.weight!==undefined&&(!Number.isFinite(q.weight)||q.weight<=0||q.weight>10))fail('El peso de una pregunta debe ser mayor que cero y máximo 10.');if(q.type!=='open'){const opts=q.options||t.options;if(!Array.isArray(opts)||opts.length<2||opts.some((o:any)=>!o.label?.trim()||!Number.isFinite(o.value))||new Set(opts.map((o:any)=>o.value)).size!==opts.length)fail('Cada pregunta necesita opciones válidas, sin valores duplicados.');}}}

export function studentInstrument(instrument:any,withExplanations=false){return {...instrument,questions:instrument.questions.map(({correctValues,explanation,...q}:any)=>({...q,...(withExplanations?{explanation}:{} )}))};}
export function resultIsReleased(row:any){return JSON.parse(row.snapshot).resultPublication!=='review'||!!db.prepare('SELECT submission_id FROM released_results WHERE submission_id=?').get(row.id);}
export function visibleSubmission(row:any,user:any){const released=resultIsReleased(row);return {...row,resultReleased:released,...(user.role==='student'?{scores:released?row.scores:'[]',snapshot:JSON.stringify(studentInstrument(JSON.parse(row.snapshot),released))}:{})};}
export function releaseResult(user:any,id:unknown){if(user.role!=='admin')fail('Solo administración puede publicar resultados.',403);const row=db.prepare('SELECT s.* FROM submissions s JOIN users u ON s.user_id=u.id WHERE s.id=? AND u.institutionId=?').get(String(id),user.institutionId) as any;if(!row)fail('Entrega no disponible.',404);db.prepare('INSERT OR IGNORE INTO released_results VALUES(?,?,?)').run(row.id,user.id,new Date().toISOString());put('institution:'+user.institutionId,'rv360:audit',[{name:user.name,action:'Publicar resultado',entity:row.id,created_at:new Date().toISOString()},...document('institution:'+user.institutionId,'rv360:audit',[])].slice(0,1000));return {ok:true};}
