const {request}=require(require('node:path').resolve('.qa-tools/node_modules/playwright')),{DatabaseSync}=require('node:sqlite'),fs=require('node:fs'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const db=new DatabaseSync('.qa-tools/constructor-qa.sqlite'),f=JSON.parse(fs.readFileSync('.qa-tools/courses-fixture.json')),base='http://localhost:3006',checks=[];
(async()=>{const a=await request.newContext({storageState:'.qa-tools/courses-admin.json'}),s=await request.newContext({storageState:'.qa-tools/courses-student.json'});async function api(ctx,path,body,method='POST',status=200){const r=await ctx.fetch(base+'/api/'+path,{method:body===undefined?'GET':method,data:body});const v=await r.json();assert.equal(r.status(),status,path+JSON.stringify(v).slice(0,450));return v;}
let state=await api(a,'training'),sim=state.simulators.find(x=>x.id===f.simulatorId&&x.version===1),course=state.courses.find(x=>x.id===f.courseId),identity={id:'',version:0,revision:0,status:'published'};
const before=db.prepare('SELECT COUNT(*) n FROM training_entities').get().n;const [p1,p2]=await Promise.all([api(a,'training/entity',{kind:'simulator',entity:{...sim,...identity,title:'Idempotencia '+Date.now()}}),Promise.resolve(null)]); // Replay exact payload below.
const payload={kind:'simulator',entity:{...sim,...identity,title:'Publicación concurrente '+Date.now()}};const published=await Promise.all([api(a,'training/entity',payload),api(a,'training/entity',payload)]);assert.equal(published[0].id,published[1].id);assert.equal(db.prepare('SELECT COUNT(*) n FROM training_entities WHERE id=?').get(published[0].id).n,1);checks.push('Publicación concurrente idempotente');
const random=await api(a,'training/entity',{kind:'simulator',entity:{...sim,...identity,title:'Banco aleatorio QA',selection:'random',quotas:[{topic:'Matemática',count:5}]}});const rc=await api(a,'training/entity',{kind:'course',entity:{...course,...identity,title:'Aleatorio QA',activities:[{...course.activities[1],simulatorId:random.id}]}});const re=await api(s,'training/enroll',{courseId:rc.id});const ra=await api(s,'training/start',{enrollmentId:re.id,activityId:'quiz',mode:'exam'});assert.equal(ra.instrument.questions.length,5);assert.equal(new Set(ra.instrument.questions.map(q=>q.id)).size,5);const rr=await api(s,'training/attempt?id='+ra.id);assert.deepEqual(rr.instrument.questions,ra.instrument.questions);checks.push('Banco aleatorio: cuota de cinco, unicidad y orden persistido');
const career=state.careers.find(x=>course.careerIds.includes(x.id)),institution=career.offers[0].institution;
const profile=await api(a,'training/entity',{kind:'profile',entity:{...identity,title:'Perfil QA aislado',institution,period:'QA 2026',level:'Grado',careerIds:[career.id],sourceUrl:'https://appcmi.ces.gob.ec/oferta_vigente/',reviewedAt:'2026-09-27',scope:'Reglas sintéticas exclusivas de pruebas; no representan convocatoria.',rules:'Fixture de validación.',internalRules:'Todos los valores de esta prueba son configuración interna.',areas:[{name:'Matemática',count:10,weight:100}],durationMinutes:30}});
await api(a,'training/entity',{kind:'simulator',entity:{...sim,...identity,title:'Incompatible QA',purpose:'admission',profileId:profile.id,profileVersion:1,areaWeights:[]}},'POST',400);
const aligned=await api(a,'training/entity',{kind:'simulator',entity:{...sim,...identity,title:'Alineación QA',purpose:'admission',profileId:profile.id,profileVersion:1,areaWeights:[{area:'Matemática',weight:100}]}});
const ac=await api(a,'training/entity',{kind:'course',entity:{...course,...identity,title:'Convocatoria QA',type:'admission',careerIds:[career.id],profileId:profile.id,profileVersion:1,activities:[{...course.activities[1],simulatorId:aligned.id}]}});
await api(s,'training/goal',{careerIds:[career.id],fields:[]},'PUT');assert((await api(s,'training')).courses.find(x=>x.id===ac.id).recommended);await api(s,'training/goal',{careerIds:[career.id],fields:[],profileId:profile.id,profileVersion:1},'PUT');assert((await api(s,'training')).courses.find(x=>x.id===ac.id).recommended);await api(s,'training/goal',{careerIds:[career.id],fields:[],profileId:profile.id,profileVersion:2},'PUT',404);checks.push('Perfil compatible: se recomienda por carrera sin convocatoria y con convocatoria exacta; versión inexistente rechazada');
const owner='institution:'+db.prepare('SELECT institutionId FROM users WHERE id=?').get(f.studentId).institutionId;let doc=db.prepare('SELECT * FROM documents WHERE owner=? AND key=?').get(owner,'rv360:custom-tests');const prior=doc?JSON.parse(doc.value):[],tid=crypto.randomUUID(),career2=course.careerIds.find(id=>id!==career.id);
const t={id:tid,stableId:tid,version:'1',schemaVersion:2,status:'Publicado',title:'Exploración QA persistida',description:'Instrumento sintético aislado',source:'Reglas QA',scoring:'total',aggregation:'sum',resultPublication:'immediate',group:'Todos los estudiantes',audience:'all',options:[{value:1,label:'Primera ruta',points:1},{value:2,label:'Otra ruta',points:2}],questions:[{id:'interest',text:'¿Qué ruta quieres explorar?',type:'single',required:true}],careerLinks:[{id:'link1',careerId:career.id,dimensionId:'General',min:1,max:1,reason:'Elegiste explorar la primera ruta.',source:'Fixture QA'},{id:'link2',careerId:career2,dimensionId:'General',min:2,max:2,reason:'Elegiste explorar otra ruta.',source:'Fixture QA'}]};
await api(a,'state',{key:'rv360:custom-tests',value:[...prior,t],revision:doc?.revision||0},'PUT');await api(s,'assessments/start',{instrumentId:tid});await api(s,'state',{key:'rv360:answers:'+tid+':1',value:{interest:1}},'PUT');await api(s,'assessments/submit',{instrumentId:tid});state=await api(s,'training');assert(state.recommendations.some(r=>r.careerId===career.id));const historic=state.enrollments.find(e=>e.id===f.enrollmentId).origin;
await api(s,'assessments/start',{instrumentId:tid});await api(s,'state',{key:'rv360:answers:'+tid+':1',value:{interest:2}},'PUT');await api(s,'assessments/submit',{instrumentId:tid});state=await api(s,'training');assert(state.recommendations.some(r=>r.careerId===career2));assert(!state.recommendations.some(r=>r.careerId===career.id));assert.deepEqual(state.enrollments.find(e=>e.id===f.enrollmentId).origin,historic);assert.equal((await api(s,'training/attempt?id='+f.attemptId)).result.revision,2);checks.push('Dos tests vocacionales entregados actualizan recomendaciones sin alterar inscripción, origen histórico ni nota académica');
const source=JSON.parse(fs.readFileSync('lib/server/data/ecuador-offer.json'));const update={source:source.source,sourceUrl:source.sourceUrl,retrievedAt:source.retrievedAt,careers:[{...source.careers[0],description:source.careers[0].description+' Revisión QA aislada.'}]};const batch=await api(a,'training/catalog/preview',{input:update});assert(batch.absent.length);const count=state.source.careerCount;await api(a,'training/catalog/apply',{id:batch.id});assert.equal((await api(a,'training')).source.careerCount,count);await api(a,'training/catalog/apply',{id:batch.id},'POST',404);checks.push('Lote CES con vista previa, aplicación una vez y conservación de carreras ausentes');
fs.writeFileSync('evidencia/cursos/extra-checks.json',JSON.stringify({checks},null,2));console.log(checks.join('\n'));await a.dispose();await s.dispose();db.close();})().catch(e=>{console.error(e);process.exitCode=1});
