const {request}=require(require('node:path').resolve('.qa-tools/node_modules/playwright')),{DatabaseSync}=require('node:sqlite'),crypto=require('node:crypto'),fs=require('node:fs'),assert=require('node:assert/strict');
const base='http://localhost:3006',db=new DatabaseSync('.qa-tools/constructor-qa.sqlite'),stamp=Date.now().toString(36),checks=[];
const admin=db.prepare("SELECT * FROM users WHERE role='admin' LIMIT 1").get();assert(admin);
function account(role,i){if(role==='admin')return admin;const id=crypto.randomUUID();db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,?,?)').run(id,'QA Cursos '+i,'cursos-'+stamp+'-'+i+'@example.test','disabled-qa-password',role,admin.institutionId,'','Activo');return {id,role,institutionId:admin.institutionId};}
function session(user,file){const token=crypto.randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(crypto.createHash('sha256').update(token).digest('hex'),user.id,Date.now()+86400000);const state={cookies:[{name:'rv360_session',value:token,domain:'localhost',path:'/',expires:Math.floor(Date.now()/1000)+86400,httpOnly:true,secure:false,sameSite:'Lax'}],origins:[]};fs.writeFileSync(file,JSON.stringify(state));return state;}
const one=account('student',1),two=account('student',2);
async function call(ctx,path='',body,method='POST',status=200){const r=await ctx.fetch(base+'/api/training'+path,{method:body===undefined?'GET':method,data:body});const text=await r.text();assert.equal(r.status(),status,path+' '+text.slice(0,600));return JSON.parse(text);}
const identity=()=>({id:'',version:0,revision:0,status:'published'});
(async()=>{
 const a=await request.newContext({storageState:session(admin,'.qa-tools/courses-admin.json')}),s=await request.newContext({storageState:session(one,'.qa-tools/courses-student.json')}),other=await request.newContext({storageState:session(two,'.qa-tools/courses-other.json')});
 const catalog=await call(a);assert(catalog.careers.length>0);const careerIds=catalog.careers.slice(0,2).map(c=>c.id);
 const upload=await a.post(base+'/api/admin/import',{multipart:{file:{name:'curso-'+stamp+'.html',mimeType:'text/html',buffer:Buffer.from('<h1>Álgebra QA '+stamp+'</h1><p>1. ¿Cuánto es 2 + 2?</p><p>a) 4</p><p>b) 5</p><script>window.PWNED=true</script>')}}});assert.equal(upload.status(),202);const job=await upload.json();let imported;
 for(let i=0;i<50;i++){const r=await a.get(base+'/api/admin/import?id='+job.id+'&status=1');imported=await r.json();if(['Completado','Error'].includes(imported.status))break;await new Promise(r=>setTimeout(r,1000));}assert.equal(imported.status,'Completado',JSON.stringify(imported));assert(imported.tests.length);assert(!JSON.stringify(imported.tests).includes('window.PWNED'));checks.push('Importación HTML real, scripts excluidos y borradores');
 const options=[{value:11,label:'Correcta'},{value:22,label:'Incorrecta'}];const questions=Array.from({length:10},(_,i)=>({id:'q'+i,text:'Pregunta '+(i+1)+' de álgebra',type:'single',policy:'objective',weight:2,topic:'Matemática',correctValues:[11],options,reviewed:true,source:'Fixture QA '+stamp,explanation:'La respuesta revisada es Correcta.'}));
 let sim={...identity(),title:'Álgebra · QA '+stamp,instrument:{id:'draft',version:'1',title:'',description:'Lee y responde. Contenido sintético de prueba.',source:'Fixture QA aislada',options:[],questions:[]},purpose:'general',modes:['practice','exam'],durationMinutes:30,maxAttempts:3,gradePolicy:'best',feedback:'question',selection:'fixed',quotas:[],areaWeights:[],questions,shuffleOptions:true,questionOrderFixedIds:['q0']};
 const preview=await call(a,'/preview/select',{simulator:sim});const answers=Object.fromEntries(questions.slice(0,9).map((q,i)=>[q.id,i<6?11:22]));const pr=await call(a,'/preview',{simulator:preview,answers});assert.equal(pr.percent,60);
 sim=await call(a,'/entity',{kind:'simulator',entity:sim});assert.equal(sim.version,1);await call(s,'/entity',{kind:'simulator',entity:sim},'POST',403);
 const course=await call(a,'/entity',{kind:'course',entity:{...identity(),title:'Fundamentos de matemática · QA '+stamp,description:'Preparación general para explorar distintas carreras.',objectives:'Repasar conceptos, practicar y revisar resultados.',level:'Introductorio',type:'general',careerIds,fields:[],activities:[{id:'read',module:'Fundamentos',title:'Conceptos básicos',kind:'text',content:'Estudia el orden de las operaciones. Después practica el simulador.',required:true,completion:'read'},{id:'quiz',module:'Práctica',title:'Practica álgebra',kind:'simulator',content:'',required:true,completion:'submit',simulatorId:sim.id,simulatorVersion:1},{id:'optional',module:'Repaso',title:'Recurso opcional',kind:'text',content:'Esta lectura no cambia el denominador.',required:false,completion:'read'}],studentIds:[],access:'all'}});
 const restricted=await call(a,'/entity',{kind:'course',entity:{...course,id:'',version:0,revision:0,title:'Acceso restringido QA '+stamp,access:'selected',studentIds:[one.id]}});
 assert(!(await call(other)).courses.some(c=>c.id===restricted.id));await call(other,'/enroll',{courseId:restricted.id},'POST',403);checks.push('Acceso por estudiante; publicación exclusiva del administrador');
 await call(s,'/goal',{careerIds,fields:[]},'PUT');let state=await call(s);assert.equal(state.courses.filter(c=>c.id===course.id&&c.recommended).length,1);
 const enrolled=await Promise.all([call(s,'/enroll',{courseId:course.id}),call(s,'/enroll',{courseId:course.id})]);assert.equal(enrolled[0].id,enrolled[1].id);const eid=enrolled[0].id;
 let e=await call(s,'/read',{enrollmentId:eid,activityId:'read'});assert.equal(e.progress.percent,50);checks.push('Curso con dos carreras deduplicado, inscripción idempotente, lectura persistida');
 let attempt=await call(s,'/start',{enrollmentId:eid,activityId:'quiz',mode:'exam'});assert(!JSON.stringify(attempt).includes('correctValues'));assert(!JSON.stringify(attempt).includes('La respuesta revisada'));const startAgain=await call(s,'/start',{enrollmentId:eid,activityId:'quiz',mode:'exam'});assert.equal(startAgain.id,attempt.id);assert.deepEqual(startAgain.instrument.questions,attempt.instrument.questions);assert.equal(startAgain.expires_at,attempt.expires_at);
 await call(other,'/attempt?id='+attempt.id,undefined,'GET',404);await call(s,'/feedback',{id:attempt.id,questionId:'q0'},'POST',403);
 attempt=await call(s,'/answers',{id:attempt.id,revision:0,answers,flags:['q9']},'PUT');await call(s,'/answers',{id:attempt.id,revision:0,answers:{},flags:[]},'PUT',409);const reloaded=await call(s,'/attempt?id='+attempt.id);assert.deepEqual(reloaded.answers,answers);assert.deepEqual(reloaded.instrument.questions,attempt.instrument.questions);
 const submitted=await Promise.all([call(s,'/finish',{id:attempt.id}),call(s,'/finish',{id:attempt.id})]);assert.equal(submitted[0].result.percent,60);assert.equal(submitted[1].result.revision,1);assert.equal(db.prepare('SELECT COUNT(*) n FROM training_results WHERE attempt_id=?').get(attempt.id).n,1);
 await call(s,'/answers',{id:attempt.id,revision:1,answers:{},flags:[]},'PUT',409);checks.push('Claves privadas, tiempo y orden estables, respuestas guardadas, concurrencia y cierre único 60%');
 state=await call(s);e=state.enrollments.find(x=>x.id===eid);assert.equal(e.progress.percent,100);assert.equal(e.grades[0].percent,60);
 const pdf=await s.get(base+'/api/training/pdf?id='+attempt.id);assert.equal(pdf.status(),200);fs.mkdirSync('evidencia/cursos',{recursive:true});fs.writeFileSync('evidencia/cursos/resultado-qa.pdf',await pdf.body());assert((await pdf.body()).subarray(0,4).toString()==='%PDF');const deniedPdf=await other.get(base+'/api/training/pdf?id='+attempt.id);assert.equal(deniedPdf.status(),404);checks.push('Progreso 100% separado de nota 60%, PDF y permisos');
 const changed=await call(a,'/entity',{kind:'simulator',entity:{...sim,version:0,revision:0,title:sim.title+' revisión',questions:sim.questions.map(q=>({...q,correctValues:[22]}))}});assert.equal(changed.version,2);assert.equal((await call(s,'/attempt?id='+attempt.id)).result.percent,60);
 await call(s,'/goal',{careerIds:[],fields:[]},'PUT');assert((await call(s)).enrollments.some(x=>x.id===eid));checks.push('Nueva versión y cambio de objetivo conservan itinerario y resultado');
 let practice=await call(s,'/start',{enrollmentId:eid,activityId:'quiz',mode:'practice'});practice=await call(s,'/answers',{id:practice.id,revision:0,answers:{q0:22},flags:[]},'PUT');await call(s,'/feedback',{id:practice.id,questionId:'q0'});practice=await call(s,'/answers',{id:practice.id,revision:1,answers:{q0:11},flags:[]},'PUT');await call(s,'/feedback',{id:practice.id,questionId:'q0'});practice=await call(s,'/finish',{id:practice.id});assert.equal(practice.result.raw,0);assert.equal(practice.result.answers.q0,22);checks.push('Práctica conserva primera respuesta confirmada y reintentos después de ayuda');
 const review=await call(a,'/review',{id:attempt.id,revision:1,reason:'Anulación QA por enunciado ambiguo',annulled:['q9'],reviews:{}});assert(Math.abs(review.result.percent-100*12/18)<1e-8);assert.equal(review.resultHistory.length,2);await call(a,'/review',{id:attempt.id,revision:1,reason:'Obsoleta',annulled:[],reviews:{}},'POST',409);checks.push('Anulación auditada y nueva revisión, conflicto de correcciones rechazado');
 let timed=await call(s,'/start',{enrollmentId:eid,activityId:'quiz',mode:'exam'});db.prepare('UPDATE training_attempts SET expires_at=? WHERE id=?').run(new Date(Date.now()-1000).toISOString(),timed.id);await new Promise(r=>setTimeout(r,6500));assert.equal(db.prepare('SELECT state FROM training_attempts WHERE id=?').get(timed.id).state,'graded');assert.equal(JSON.parse(db.prepare('SELECT result FROM training_results WHERE attempt_id=?').get(timed.id).result).percent,0);checks.push('Vencimiento sin peticiones del navegador calcula cero para todas las omisiones');
 const rubricQ={...questions[0],id:'essay',type:'open',policy:'rubric',rubric:[{id:'clarity',label:'Claridad',levels:[{id:'none',label:'Sin evidencia',points:0},{id:'full',label:'Completo',points:2}]}]};
 const rubricSim=await call(a,'/entity',{kind:'simulator',entity:{...sim,id:'',version:0,revision:0,title:'Rúbrica QA '+stamp,questions:[rubricQ]}});const rc=await call(a,'/entity',{kind:'course',entity:{...course,id:'',version:0,revision:0,title:'Escritura QA '+stamp,activities:[{...course.activities[1],simulatorId:rubricSim.id,completion:'score',target:60}]}});const re=await call(s,'/enroll',{courseId:rc.id});let ra=await call(s,'/start',{enrollmentId:re.id,activityId:'quiz',mode:'exam'});await call(s,'/answers',{id:ra.id,revision:0,answers:{essay:'Explico el procedimiento.'},flags:[]},'PUT');ra=await call(s,'/finish',{id:ra.id});assert.equal(ra.result.percent,null);ra=await call(a,'/review',{id:ra.id,revision:1,reason:'Evaluación de claridad',reviews:{essay:{clarity:'full'}}});assert.equal(ra.result.percent,100);assert.equal((await call(s)).enrollments.find(x=>x.id===re.id).progress.percent,100);ra=await call(a,'/review',{id:ra.id,revision:2,reason:'Corrección justificada QA',reviews:{essay:{clarity:'none'}}});assert.equal((await call(s)).enrollments.find(x=>x.id===re.id).progress.percent,0);checks.push('Rúbrica pendiente, revisión y recálculo de avance cuando cambia la nota');
 fs.writeFileSync('.qa-tools/courses-fixture.json',JSON.stringify({courseId:course.id,enrollmentId:eid,attemptId:attempt.id,studentId:one.id,simulatorId:sim.id,checks}));fs.writeFileSync('evidencia/cursos/api-checks.json',JSON.stringify({date:new Date().toISOString(),checks},null,2));console.log(checks.join('\n'));await a.dispose();await s.dispose();await other.dispose();db.close();
})().catch(e=>{console.error(e);process.exitCode=1});
