const {chromium}=require(require('node:path').resolve('.qa-tools/node_modules/playwright')),fs=require('node:fs'),assert=require('node:assert/strict');
const base='http://localhost:3006',dir='evidencia/cursos',fixture=JSON.parse(fs.readFileSync('.qa-tools/courses-fixture.json'));
(async()=>{const b=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),issues=[],checks=[];
const admin=await b.newContext({storageState:'.qa-tools/courses-admin.json',viewport:{width:1366,height:900}}),student=await b.newContext({storageState:'.qa-tools/courses-student.json',viewport:{width:1366,height:900}}),p=await admin.newPage(),s=await student.newPage();
for(const page of[p,s])page.on('pageerror',e=>issues.push(e.message));
await p.goto(base+'/admin/cursos');await p.getByRole('heading',{name:/^Cursos(?: de autopreparación)?$/,exact:true}).waitFor();await p.getByRole('button',{name:'Crear curso',exact:true}).waitFor();await p.screenshot({path:dir+'/admin-desktop.png',fullPage:true});
await p.getByRole('button',{name:'Crear curso',exact:true}).click();await p.getByLabel('Nombre del curso',{exact:true}).fill('Curso creado desde interfaz QA');await p.getByLabel('Descripción',{exact:true}).fill('Curso de prueba visual con datos aislados.');await p.getByLabel('Objetivos de aprendizaje').fill('Verificar la edición y el guardado.');await p.getByRole('button',{name:'Añadir actividad'}).click();await p.getByLabel('Título de actividad').fill('Lectura de prueba');await p.getByLabel('Contenido de la lección').fill('Repasa los conceptos y confirma la lectura.');await p.getByRole('button',{name:'Guardar borrador',exact:true}).click();await p.waitForTimeout(800);await p.screenshot({path:dir+'/editor-desktop.png',fullPage:true});await p.getByRole('button',{name:'Cerrar ventana'}).click();checks.push('Crear y guardar borrador desde controles visuales');
await p.getByRole('button',{name:'Simuladores y preguntas',exact:true}).click();await p.getByRole('button',{name:'Crear simulador',exact:true}).click();await p.getByRole('button',{name:'2. Preguntas',exact:true}).click();await p.getByRole('button',{name:'Añadir pregunta',exact:true}).click();await p.getByLabel('Enunciado',{exact:true}).fill('¿Qué opción completa la igualdad?');await p.screenshot({path:dir+'/pregunta-desktop.png',fullPage:true});await p.getByRole('button',{name:'Cerrar ventana'}).click();
await s.goto(base+'/mi-ruta/cursos');await s.getByRole('button',{name:'Mis cursos',exact:true}).waitFor();await s.getByRole('button',{name:'Mis cursos',exact:true}).click();await s.getByRole('button',{name:'Ver resultados',exact:true}).first().click();await s.getByText('Practica álgebra',{exact:true}).waitFor();await s.screenshot({path:dir+'/curso-desktop.png',fullPage:true});
await s.getByRole('button',{name:'Iniciar práctica',exact:true}).click();await s.getByRole('button',{name:'Guardar respuestas',exact:true}).waitFor();await s.getByText('Correcta',{exact:true}).click();await s.getByRole('button',{name:'Guardar respuestas',exact:true}).click();await s.getByText('Respuestas confirmadas por el servidor.',{exact:true}).waitFor();await s.screenshot({path:dir+'/simulador-desktop.png',fullPage:true});await s.getByRole('button',{name:'Guardar y volver',exact:true}).click();checks.push('Abrir curso, iniciar práctica y guardar respuesta desde interfaz');
async function capture(page,path,width,name,setup){await page.setViewportSize({width,height:900});await page.goto(base+path);await page.getByRole('heading',{name:/^Cursos(?: de autopreparación)?$/,exact:true}).waitFor();await page.waitForTimeout(500);if(setup)await setup(page);const size=await page.evaluate(()=>({w:innerWidth,doc:document.documentElement.scrollWidth}));assert(size.doc<=size.w+1,JSON.stringify({name,width,...size}));await page.screenshot({path:`${dir}/${name}-${width}.png`,fullPage:true});checks.push(`${name} ${width}px: sin desbordamiento horizontal`);}
for(const width of[360,390,768,1024,1366]){await capture(p,'/admin/cursos',width,'admin');await capture(s,'/mi-ruta/cursos',width,'estudiante');await capture(p,'/admin/cursos',width,'editor',async x=>{await x.getByRole('button',{name:'Crear curso',exact:true}).click();});}
await p.setViewportSize({width:1366,height:900});await p.goto(base+'/admin/cursos');await p.getByRole('button',{name:'Crear curso',exact:true}).waitFor();const cdp=await admin.newCDPSession(p);await cdp.send('Emulation.setDeviceMetricsOverride',{width:683,height:450,deviceScaleFactor:2,mobile:false});await p.getByRole('button',{name:'Crear curso',exact:true}).click();await p.screenshot({path:dir+'/admin-editor-200-percent.png',fullPage:true});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));checks.push('Reflujo equivalente a 200%: escritorio 1366px con viewport CSS 683px');
assert.equal(issues.length,0,issues.join('\n'));fs.writeFileSync(dir+'/visual-checks.json',JSON.stringify({checks,issues},null,2));console.log(checks.join('\n'));await b.close();})().catch(e=>{console.error(e);process.exitCode=1});
