import { NextRequest,NextResponse } from 'next/server';
import { randomUUID } from 'node:crypto';
import { mkdir,writeFile,readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { requireUser,fail,hash,document,put,rateLimit } from '@/lib/server/store';
import { startJob,cancelJob,importFolder } from '@/lib/server/import-jobs';
export const runtime='nodejs';
export async function POST(req:NextRequest){try{const user=await requireUser(true);if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)fail('Origen no autorizado.',403);const owner='institution:'+user.institutionId;if(req.headers.get('content-type')?.includes('application/json')){const body=await req.json();if(body.action==='cancel')cancelJob(owner,body.id);else if(body.action==='retry')await startJob(owner,body.id);else fail('Operación no válida.');return NextResponse.json({ok:true});}rateLimit('import:'+user.id);if(Number(req.headers.get('content-length')||0)>11000000)fail('El límite por archivo es 10 MB.',413);const form=await req.formData(),file=form.get('file');if(!(file instanceof File)||file.size>10000000||file.size<5)fail('Selecciona un archivo de hasta 10 MB.');if(!/\.(pdf|docx|html?|htm)$/i.test(file.name))fail('Selecciona PDF, Word (.docx) o HTML. Convierte .doc a .docx.');const bytes=Buffer.from(await file.arrayBuffer()),digest=hash(bytes.toString('base64'));const previous=document(owner,'rv360:imports',[]);if(previous.some((f:any)=>f.hash===digest))fail('Este documento ya fue importado. Revisa su estado en el historial de importaciones.');const id=randomUUID(),folder=importFolder();await mkdir(folder,{recursive:true});await writeFile(resolve(folder,id),bytes,{flag:'wx'});const current=document(owner,'rv360:imports',[]);if(current.some((f:any)=>f.hash===digest))fail('Este documento ya fue importado. Revisa su estado en el historial de importaciones.');put(owner,'rv360:imports',[...current,{id,name:file.name.slice(0,180),hash:digest,author:user.name,created_at:new Date().toISOString(),status:'Pendiente',progress:0}]);await startJob(owner,id);return NextResponse.json({id,status:'Procesando'},{status:202});}catch(e:any){return NextResponse.json({error:e.status?e.message:'No se pudo iniciar la importación.'},{status:e.status||422});}}
export async function GET(req:NextRequest){try{const user=await requireUser(true),id=req.nextUrl.searchParams.get('id');const record=document('institution:'+user.institutionId,'rv360:imports',[]).find((r:any)=>r.id===id);if(!record)fail('Documento no encontrado.',404);if(req.nextUrl.searchParams.has('status'))return NextResponse.json({...record,tests:record.tests?.map((t:any)=>({...t,sourceId:record.id}))},{headers:{'Cache-Control':'no-store'}});const file=await readFile(/*turbopackIgnore: true*/ resolve(importFolder(),record.id));return new NextResponse(file,{headers:{'Content-Type':'application/octet-stream','Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(record.name),'X-Content-Type-Options':'nosniff','Cache-Control':'no-store'}});}catch(e:any){return NextResponse.json({error:e.message},{status:e.status||500});}}
