import { useState } from 'react';
import type { Instrument,Question } from '../../types';
import { Card,Field,SelectField,TextareaField,Notice,Button } from '../../components/ui/primitives';
export function InstrumentSettings({value,onChange}:{value:Instrument;onChange:(patch:Partial<Instrument>)=>void}){
 return <Card className="stack"><h3>Aplicación y resultados</h3><div className="grid grid-2"><Field label="Batería o conjunto (opcional)" maxLength={120} value={value.battery||''} onChange={e=>onChange({battery:e.target.value})}/><Field label="Disponible desde" type="date" value={value.availableFrom||''} onChange={e=>onChange({availableFrom:e.target.value})}/><Field label="Duración estimada en minutos (0 = sin estimación)" type="number" min={0} max={480} value={value.estimatedMinutes||0} onChange={e=>onChange({estimatedMinutes:Number(e.target.value)})}/><SelectField label="Publicar resultados" value={value.resultPublication||'immediate'} onChange={e=>onChange({resultPublication:e.target.value as Instrument['resultPublication']})}><option value="immediate">Al entregar</option><option value="review">Después de revisión administrativa</option><option value="date">En una fecha determinada</option></SelectField>{value.resultPublication==='date'&&<Field label="Publicar resultados desde (hora de Ecuador)" type="datetime-local" value={value.releaseAt?.slice(0,16)||''} onChange={e=>onChange({releaseAt:e.target.value?e.target.value+':00-05:00':undefined})}/>}<Field label="Tiempo máximo de respuesta en minutos (0 = sin límite)" type="number" min={0} max={480} value={value.durationMinutes||0} onChange={e=>onChange({durationMinutes:Number(e.target.value)})}/></div><p className="small muted">La estimación es orientativa. Si configuras un tiempo máximo, el servidor controla el plazo desde el inicio confirmado. Cada batería conserva los resultados y reglas de sus instrumentos por separado.</p>{value.scoring!=='manual'&&<SelectField label="Interpretar rangos sobre" value={value.aggregation||'mean'} onChange={e=>onChange({aggregation:e.target.value as Instrument['aggregation']})}><option value="mean">Promedio ponderado</option><option value="sum">Suma ponderada</option></SelectField>}</Card>;
}
export function QuestionSettings({value,onChange,options,objective,images=[]}:{images?:{src:string;source:string}[];value:Question;onChange:(patch:Partial<Question>)=>void;options:{value:number;label:string}[];objective:boolean}){
 const[error,setError]=useState('');
 return <div className="stack-sm"><label className="row"><input type="checkbox" checked={value.required!==false} onChange={e=>onChange({required:e.target.checked})}/> Respuesta obligatoria</label><Field label="Imagen de la pregunta (PNG, JPEG o WebP, hasta 250 KB)" type="file" accept="image/png,image/jpeg,image/webp" onChange={async e=>{setError('');const file=e.target.files?.[0];if(!file)return;if(file.size>250000||!['image/png','image/jpeg','image/webp'].includes(file.type)){setError('Selecciona una imagen PNG, JPEG o WebP de hasta 250 KB.');return;}const reader=new FileReader();reader.onerror=()=>setError('No se pudo leer la imagen.');reader.onload=()=>onChange({image:String(reader.result)});reader.readAsDataURL(file);}}/>{error&&<Notice tone="danger">{error}</Notice>}{value.image&&<><img className="assessment-image" src={value.image} alt={value.imageAlt||'Imagen pendiente de describir'}/><Field label="Descripción accesible de la imagen" required value={value.imageAlt||''} onChange={e=>onChange({imageAlt:e.target.value})}/><Button size="sm" variant="ghost" onClick={()=>onChange({image:undefined,imageAlt:undefined})}>Quitar imagen</Button></>}<>{images.length>0&&<details><summary>Imágenes extraídas del documento ({images.length})</summary><div className="grid grid-2">{images.map((image,i)=><Card key={i}><img className="assessment-image" src={image.src} alt={image.source}/><Button size="sm" variant="secondary" onClick={()=>onChange({image:image.src})}>Usar {image.source}</Button></Card>)}</div></details>}</><TextareaField label="Explicación al publicar el resultado (opcional)" maxLength={3000} value={value.explanation||''} onChange={e=>onChange({explanation:e.target.value})}/>{objective&&<fieldset className="preview-question"><legend>Clave de respuesta correcta</legend><div className="preview-options">{options.map(o=><label key={o.value}><input type={value.type==='multiple'?'checkbox':'radio'} name={'key-'+value.id} checked={(value.correctValues||[]).includes(o.value)} onChange={e=>onChange({correctValues:value.type==='multiple'?(e.target.checked?[...(value.correctValues||[]),o.value]:(value.correctValues||[]).filter(v=>v!==o.value)):[o.value]})}/>{o.label}</label>)}</div></fieldset>}</div>;
}
