import { useEffect,useState } from 'react';
import { Check,Send,Archive,FileCheck } from 'lucide-react';
import { previewAction,flush } from '../../lib/session';
import { Badge,Button,Card,Notice,SectionTitle,SelectField } from '../../components/ui/primitives';
type Version={id:string;kind:string;item_id:string;version:number;status:string;created_at:string};
export function PublicationCenter({kind,items}:{kind:'instrument'|'content';items:{id:string;title:string}[]}){
 const[id,setId]=useState(items[0]?.id||''),[versions,setVersions]=useState<Version[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{try{const result=await previewAction('admin/versions');setVersions(result.items);}catch(e){setError((e as Error).message);}};useEffect(()=>{void load();},[]);
 const act=async(method:string,body:unknown)=>{setBusy(true);setError('');try{await flush();await previewAction('admin/versions',{method,body:JSON.stringify(body)});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <Card className="stack"><SectionTitle title="Revisión y publicación"/><p className="muted small">Guarda el borrador y envíalo a revisión. Cada publicación conserva una copia independiente. Las respuestas anteriores mantienen su versión original.</p><div className="row"><SelectField label={kind==='instrument'?'Instrumento':'Contenido'} value={id} onChange={e=>setId(e.target.value)}>{items.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</SelectField><Button variant="secondary" loading={busy} disabled={!id} icon={<Send size={16}/>} onClick={()=>void act('POST',{kind,itemId:id})}>Enviar a revisión</Button></div>{error&&<Notice tone="danger">{error}</Notice>}{versions.filter(v=>v.kind===kind&&v.item_id===id).map(version=><div className="version-row" key={version.id}><div><h3>Versión {version.version}</h3><p>{new Date(version.created_at).toLocaleString('es-EC')}</p></div><Badge tone={version.status==='Publicado'?'success':version.status==='Archivado'?'neutral':'warning'}>{version.status}</Badge><div className="row">{version.status==='En revisión'&&<Button size="sm" variant="secondary" disabled={busy} onClick={()=>void act('PATCH',{id:version.id,status:'Revisado'})} icon={<Check size={15}/>}>Marcar revisado</Button>}{version.status==='Revisado'&&<Button size="sm" disabled={busy} onClick={()=>void act('PATCH',{id:version.id,status:'Publicado'})} icon={<FileCheck size={15}/>}>Publicar</Button>}{version.status!=='Archivado'&&<Button size="sm" variant="ghost" disabled={busy} onClick={()=>void act('PATCH',{id:version.id,status:'Archivado'})} icon={<Archive size={15}/>}>Archivar</Button>}</div></div>)}{!versions.some(v=>v.kind===kind&&v.item_id===id)&&<p className="muted small">Todavía no se han enviado versiones de este contenido.</p>}</Card>;
}
export function AuditLog(){const[rows,setRows]=useState<{name:string;action:string;entity:string;created_at:string}[]>([]),[error,setError]=useState('');useEffect(()=>{previewAction('admin/audit').then(r=>setRows(r.items)).catch(e=>setError(e.message));},[]);return <Card className="stack"><SectionTitle title="Historial de cambios"/>{error?<Notice tone="warning">{error}</Notice>:<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Fecha</th><th>Responsable</th><th>Acción</th><th>Contenido</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td>{new Date(r.created_at).toLocaleString('es-EC')}</td><td>{r.name}</td><td>{r.action}</td><td>{r.entity}</td></tr>)}{!rows.length&&<tr><td colSpan={4}>Aún no hay cambios administrativos registrados.</td></tr>}</tbody></table></div>}</Card>;}
