import {useState} from 'react';
import type {Instrument} from '../../types';
import {Dialog} from '../../components/ui/Dialog';
import {Button,Notice} from '../../components/ui/primitives';
import {TestQuestion} from '../../components/domain/TestQuestion';
import {visibleQuestions} from '../../lib/test-engine';
export function TestPreview({instrument,onClose}:{instrument:Instrument;onClose:()=>void}){
 const[answers,setAnswers]=useState<Record<string,any>>({}),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <Dialog open title={'Simular · '+(instrument.title||'Nuevo test')} onClose={onClose} wide><div className="stack assessment-preview"><Notice>Simulación administrativa. No crea intentos ni altera estadísticas de estudiantes.</Notice>{visibleQuestions(instrument,answers).map((q,i)=><fieldset className="preview-question" key={q.id}><legend>{i+1}. {q.text}{q.required===false?' · Opcional':''}</legend><TestQuestion instrument={instrument} question={q} value={answers[q.id]} onChange={v=>{setAnswers({...answers,[q.id]:v});setResult(null);}}/></fieldset>)}{error&&<Notice tone="danger">{error}</Notice>}<div className="row"><Button loading={busy} onClick={async()=>{setBusy(true);setError('');try{const response=await fetch('/api/admin/tests/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({instrument,answers})});if(!response.headers.get('content-type')?.includes('application/json'))throw new Error('La simulación necesita el servidor de la plataforma. Abre esta página en la instalación conectada.');const data=await response.json();if(!response.ok)throw new Error(data.error);setResult(data);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Calcular resultado de prueba</Button><Button variant="secondary" onClick={()=>{setAnswers({});setResult(null);}}>Reiniciar</Button></div>{result&&<section className="stack" aria-live="polite"><h3>Resultado de la simulación</h3><p>Motor {result.engineVersion} · {result.state==='pending-review'?'Pendiente de rúbrica':result.state==='insufficient'?'Cobertura insuficiente':'Calculado'}</p><p>{result.coverage.responded} de {result.coverage.applicable} respuestas aplicables · {result.coverage.pending} pendientes de revisión</p>{result.scores.length?<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Resultado</th><th>Puntuación</th><th>Recorrido aplicable</th><th>Interpretación</th></tr></thead><tbody>{result.scores.map((s:any)=><tr key={s.dimension}><th>{instrument.dimensions?.find(d=>d.id===s.dimension)?.name||s.dimension}</th><td>{s.value.toLocaleString('es-EC',{maximumFractionDigits:2})}</td><td>{s.min} a {s.max}{s.normalized!==undefined?' · '+s.normalized.toFixed(2)+' / 100 del recorrido':''}</td><td>{s.band||'Sin interpretación configurada'}</td></tr>)}</tbody></table></div>:<Notice tone="neutral">Las respuestas se conservan sin puntuación final.</Notice>}<details><summary>Trazabilidad por pregunta</summary><div className="stack-sm">{result.trace.map((r:any,i:number)=><div className="card" key={i}><b>{instrument.questions.find(q=>q.id===r.questionId)?.text}</b><p>{r.state||`${r.dimension}: ${r.contribution} × peso ${r.weight} = ${r.subtotal}`}</p></div>)}</div></details></section>}</div></Dialog>;
}
