import { useState } from 'react';
import type { Instrument } from '../../types';
import { Dialog } from '../../components/ui/Dialog';
import { Button,Notice,TextareaField } from '../../components/ui/primitives';
import { dimensions } from '../../data/instruments';

type Score={dimension:string;raw:number;value:number;percent?:number;band?:string};
export function TestPreview({instrument,onClose}:{instrument:Instrument;onClose:()=>void}){
 const[answers,setAnswers]=useState<Record<string,number|number[]|string>>({}),[scores,setScores]=useState<Score[]|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const answer=(id:string,value:number|number[]|string)=>{setAnswers(previous=>({...previous,[id]:value}));setScores(null);setError('');};
 const calculate=async()=>{setBusy(true);setError('');setScores(null);try{const response=await fetch('/api/admin/tests/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({instrument,answers})});const result=await response.json();if(!response.ok)throw new Error(result.error);setScores(result.scores);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <Dialog open title={instrument.title||'Probar como estudiante'} onClose={onClose} wide><div className="stack assessment-preview"><Notice>Prueba como estudiante. Estas respuestas se usan solo para comprobar el instrumento: no se guardan ni cuentan en los resultados de tu institución.</Notice><p className="muted">{instrument.description}</p>{instrument.questions.map((q,index)=><fieldset className="preview-question" key={q.id}><legend>{index+1}. {q.text}{q.required===false?' · Opcional':''}</legend>{q.image&&<img className="assessment-image" src={q.image} alt={q.imageAlt||''}/>}{q.type==='open'?<TextareaField label="Tu respuesta de prueba" value={String(answers[q.id]||'')} onChange={e=>answer(q.id,e.target.value)}/>:<div className="preview-options">{(q.options||instrument.options).map(o=>{const multiple=q.type==='multiple',selected=multiple?Array.isArray(answers[q.id])&&(answers[q.id] as number[]).includes(o.value):answers[q.id]===o.value;return <label key={o.value} className={selected?'selected':''}><input type={multiple?'checkbox':'radio'} name={'preview-'+q.id} checked={selected} onChange={()=>answer(q.id,multiple?(selected?(answers[q.id] as number[]).filter(v=>v!==o.value):[...(Array.isArray(answers[q.id])?answers[q.id] as number[]:[]),o.value]):o.value)}/><span>{o.label}</span></label>;})}</div>}</fieldset>)}{error&&<Notice tone="danger">{error}</Notice>}<div className="row"><Button loading={busy} onClick={()=>void calculate()}>Calcular resultado de prueba</Button><Button variant="secondary" disabled={busy} onClick={()=>{setAnswers({});setScores(null);setError('');}}>Reiniciar prueba</Button></div>{scores!==null&&<section className="preview-result stack" aria-live="polite"><h3>Resultado de prueba</h3><p className="muted small">Motor de evaluación · versión 1. No es una entrega de estudiante.</p>{scores.length?<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Dimensión</th><th>Suma</th><th>Promedio</th><th>Interpretación</th></tr></thead><tbody>{scores.map(s=><tr key={s.dimension}><th scope="row">{dimensions.find(d=>d.code===s.dimension)?.name||s.dimension}</th><td>{s.raw}</td><td>{s.value.toFixed(2)}</td><td>{s.percent!==undefined?`${s.percent} / 100`:s.band||'Sin rango configurado'}</td></tr>)}</tbody></table></div>:<Notice tone="neutral">Respuestas completas. Este instrumento conserva las respuestas sin cálculo automático.</Notice>}</section>}</div></Dialog>;
}
