import Link from 'next/link';
import {ArrowRight,ClipboardCheck,CheckCircle2,FileText} from 'lucide-react';
import {useEffect,useState} from 'react';
import {useSession,previewAction} from '../../lib/session';
import {answerKey,completion,instruments} from '../../data/instruments';
import {Badge,Card,Progress,PageHeader} from '../../components/ui/primitives';
import type {Instrument} from '../../types';
export function testHref(t:Instrument){return ['intereses','valores','autoconocimiento'].includes(t.id)?'/evaluacion/'+t.id:'/evaluacion/personalizada?id='+encodeURIComponent(t.id);}
export function useAssignedTests(){const s=useSession();const battery=s.values['rv360:battery'];const tests=(battery?.instruments||instruments) as Instrument[];const custom=(s.values['rv360:custom-tests']||[]) as Instrument[];const all=[...tests,...custom.filter(t=>!tests.some(b=>b.id===t.id&&b.version===t.version))];const rows=(list:Instrument[])=>list.map(t=>({test:t,count:completion(t,s.values[answerKey(t)]||{}),submission:(s.values['rv360:submissions']||[]).find((r:any)=>r.instrument_id===t.id&&r.version===t.version)}));return {battery:rows(tests),all:rows(all),frozen:!!battery?.frozen};}
function availability(t:Instrument){const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Guayaquil'}).format(new Date());return t.availableFrom&&today<t.availableFrom?'Disponible desde '+t.availableFrom:t.due&&today>t.due?'Plazo terminado':'';}
function TestRows({rows}:{rows:ReturnType<typeof useAssignedTests>['all']}){return <div className="compact-test-list">{rows.map(({test,count,submission})=><div className="compact-test-row" key={test.id+test.version}><span className={'icon-tile '+(submission?'teal':'')}>{submission?<CheckCircle2 size={21}/>:<ClipboardCheck size={21}/>}</span><div className="compact-test-copy"><h2>{test.title}</h2><p>{test.description}</p><small>{test.questions.length} preguntas · {submission?'Entregado':count?`${count} respuestas guardadas`:'Sin comenzar'}</small></div><Badge tone={submission?'success':count?'primary':'neutral'}>{submission?'Completado':count?'En curso':'Pendiente'}</Badge>{!submission&&availability(test)?<span className="small muted">{availability(test)}</span>:<Link className="button button--secondary button--sm" href={submission?'/mi-ruta/resultados':testHref(test)}>{submission?'Ver resultado':count?'Continuar':'Comenzar'}<ArrowRight size={16}/></Link>}</div>)}</div>;}
export function CompactDashboard(){const s=useSession(),{battery}=useAssignedTests(),[reports,setReports]=useState<any[]>([]);useEffect(()=>{previewAction('reports/guidance').then(r=>setReports(r.items)).catch(()=>{});},[]);const complete=battery.filter(r=>r.submission).length,next=battery.find(r=>!r.submission&&!availability(r.test)),last=reports.find(r=>r.status==='available');
return <><PageHeader title={'Hola, '+(s.user?.name.split(' ')[0]||'')} description="Un paso a la vez para comprender tus intereses."/><Card className="compact-next"><div><span className="eyebrow">TU SIGUIENTE PASO</span><h2>{last&&!next?'Tu reporte está disponible':next?next.count?'Retoma donde lo dejaste':'Empieza por conocerte':'Ya entregaste tus tests'}</h2><p>{next?next.test.title:'Consulta tus resultados y el estado de tu informe de orientación.'}</p><Link className="button button--primary button--md" href={next?testHref(next.test):'/mi-ruta/resultados'}>{next?next.count?'Continuar evaluación':'Comenzar mis tests':last?'Ver mi reporte':'Ver mis resultados'}<ArrowRight size={18}/></Link></div><div className="compact-progress"><ClipboardCheck size={28}/><strong>{complete} de {battery.length}</strong><span>tests completados</span><Progress value={complete} total={battery.length} label="Progreso de mi evaluación"/></div></Card><section className="compact-section"><div className="section-title"><h2>Tu evaluación</h2><span className="muted small">{battery.length-complete} pendientes · {complete} completados</span></div>{battery.length?<TestRows rows={battery}/>:<Card>No tienes tests asignados. Tu institución los publicará aquí.</Card>}</section>{last&&<Link className="compact-report-link" href="/mi-ruta/resultados"><FileText/><span><b>Último reporte</b><small>{new Date(last.createdAt).toLocaleDateString('es-EC')}</small></span><ArrowRight/></Link>}</>;
}
export function CompactTests(){const {all,frozen}=useAssignedTests();return <><PageHeader title="Mis tests" description="Responde a tu ritmo. Puedes guardar y continuar después."/><TestRows rows={all}/><p className="compact-footnote">No hay respuestas correctas o incorrectas en los cuestionarios de autoexploración.{frozen?' Tu evaluación conserva las versiones con las que comenzaste.':''}</p></>;}
