import {PagedList} from '../../components/ui/PagedList';
import { useSearchParams } from 'next/navigation';
import { ClipboardList } from 'lucide-react';
import Link from 'next/link';
import { useSession } from '../../lib/session';
import { answerKey,completion } from '../../data/instruments';
import { Badge,Card,PageHeader } from '../../components/ui/primitives';
import { FocusShell } from '../../components/layout/Shells';
import { Questionnaire } from '../../components/domain/Questionnaire';
import type { Navigate } from '../../types';
import type { CustomTest } from '../admin/TestManager';
type AssignedTest=CustomTest&{availability?:'open'|'future'|'closed'};
export function CustomTests(){const state=useSession();const tests=(state.values['rv360:custom-tests']||[]) as AssignedTest[];if(!tests.length)return null;return <section className="stack"><h2>Asignados por tu institución</h2><PagedList className="grid grid-3" label="tests asignados">{tests.map(test=>{const count=completion(test,state.values[answerKey(test)]||{}),submission=(state.values['rv360:submissions']||[]).find((s:any)=>s.instrument_id===test.id&&s.version===test.version),closed=test.availability==='closed'||test.availability==='future';const status=submission?(submission.resultReleased===false?'En revisión':JSON.parse(submission.scores).length?'Con resultados':'Entregado'):closed?(test.availability==='future'?'Próximamente':'Plazo finalizado'):count?'En curso':'Pendiente';return <Card className="test-manager-card" key={test.id}><div className="row between"><span className="icon-tile"><ClipboardList/></span><Badge tone={submission?'success':count?'primary':'neutral'}>{status}</Badge></div><h3>{test.title}</h3>{test.battery&&<Badge tone="neutral">{test.battery}</Badge>}<p className="muted small">{test.description}</p><p className="muted small">{count} de {test.questions.length} preguntas{test.due?' · Hasta '+test.due:''}{test.availableFrom?' · Desde '+test.availableFrom:''}{test.estimatedMinutes?' · '+test.estimatedMinutes+' min estimados':''}</p>{submission?<Link className="button button--secondary button--md" href="/mi-ruta/resultados">Ver entrega y resultados</Link>:closed?<p className="small muted">{test.availability==='future'?'Podrás comenzar en la fecha indicada.':'Consulta a tu institución si necesitas una nueva asignación.'}</p>:<Link className="button button--secondary button--md" href={'/evaluacion/personalizada?id='+encodeURIComponent(test.id)}>{count?'Continuar test':'Comenzar test'}</Link>}</Card>;})}</PagedList></section>;}
export function CustomAssessment({navigate}:{navigate:Navigate}){const params=useSearchParams(),state=useSession();const test=([...(state.values['rv360:battery']?.instruments||[]),...(state.values['rv360:custom-tests']||[])] as AssignedTest[]).find(t=>t.id===params.get('id')&&t.status==='Publicado');const available=test&&(!test.availability||test.availability==='open');return <FocusShell title={test?.title||'Evaluación'} navigate={navigate}>{available?<Questionnaire key={test.id} instrument={test} navigate={navigate}/>:<Card><PageHeader title="Este test no está disponible" description={test?.availability==='future'?'Disponible desde '+test.availableFrom:'Vuelve a tus evaluaciones para consultar los tests publicados y sus plazos.'}/><Link className="button button--primary button--md" href="/mi-ruta/evaluaciones">Mis evaluaciones</Link></Card>}</FocusShell>;}
