import { useEffect,useState } from 'react';
import { Download,FileText } from 'lucide-react';
import { Button,Card,Checkbox,Notice,SectionTitle,SelectField } from '../../components/ui/primitives';
import { Dialog } from '../../components/ui/Dialog';
import { previewAction,useSession } from '../../lib/session';
import { downloadIntegralReport } from '../../lib/reports';
import { versionLabel } from '../../lib/version';
import type { Submission } from '../../lib/reports';
import type { IntegralReport,IntegralSummary } from '../../lib/integral-report';

export function IntegralReports({studentId}:{studentId?:string}){
 const session=useSession(),student=session.user?.role==='student',attempts=(session.values['rv360:submissions']||[]) as Submission[];
 const[items,setItems]=useState<IntegralSummary[]>([]),[report,setReport]=useState<IntegralReport|null>(null),[creating,setCreating]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[shared,setShared]=useState(false),[chosen,setChosen]=useState<Record<string,string>>({});
 const groups=[...new Set(attempts.map(a=>a.instrument_id))];
 const load=()=>previewAction('reports/integral'+(studentId?'?studentId='+encodeURIComponent(studentId):'')).then(r=>setItems(r.items)).catch(e=>setError(e.message));
 useEffect(()=>{void load();},[studentId]);
 const open=async(id:string)=>{setBusy(true);setError('');try{setReport(await previewAction('reports/integral/detail?id='+encodeURIComponent(id)));}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <><Card className="stack integral-reports"><SectionTitle title={student?'Informe integral de mi ruta':'Informes integrales compartidos'}/><p className="muted">Una copia fechada con evaluaciones, carreras sugeridas, plan, reflexiones y actividades. Conserva los datos y las reglas utilizados al generarla.</p>{student&&<Button icon={<FileText size={17}/>} disabled={!attempts.length} onClick={()=>{setChosen(Object.fromEntries(groups.map(id=>[id,attempts.find(a=>a.instrument_id===id)!.id])));setShared(false);setError('');setCreating(true);}}>Generar informe integral</Button>}{!items.length&&<p className="small muted">{student?'Todavía no has generado un informe integral. Necesitas al menos una evaluación entregada.':'Este estudiante todavía no ha compartido un informe integral con su institución.'}</p>}{items.map(item=><div className="integral-history row between" key={item.id}><div><b>{new Date(item.createdAt).toLocaleString('es-EC')}</b><p className="small muted">{item.shared?'Compartido con la institución':'Solo para mí'} · {item.engineVersion}</p></div><Button size="sm" variant="secondary" disabled={busy} onClick={()=>void open(item.id)}>Ver informe integral</Button></div>)}{error&&<Notice tone="danger">{error}</Notice>}</Card>
 <Dialog open={creating} title="Preparar mi informe integral" onClose={()=>setCreating(false)} wide><div className="stack"><p>Selecciona un intento por instrumento. Se incluirán las reflexiones, actividades y el plan guardados en este momento.</p>{groups.map(id=><SelectField key={id} label={JSON.parse(attempts.find(a=>a.instrument_id===id)!.snapshot||'{}').title||id} value={chosen[id]||''} onChange={e=>setChosen({...chosen,[id]:e.target.value})}><option value="">No incluir</option>{attempts.filter(a=>a.instrument_id===id).map(a=><option value={a.id} key={a.id}>{new Date(a.created_at).toLocaleString('es-EC')} · {versionLabel(a.version)} · {a.id.slice(0,8)}</option>)}</SelectField>)}{!!session.user?.institutionId&&<Checkbox label="Compartir esta copia con la administración y orientación autorizada de mi institución, incluidas mis reflexiones y plan." checked={shared} onChange={e=>setShared(e.target.checked)}/>}<Notice>Si después cambias tus respuestas o tu plan, genera otra copia. Este informe conservará su contenido original.</Notice>{error&&<Notice tone="danger">{error}</Notice>}<Button loading={busy} disabled={!Object.values(chosen).some(Boolean)} onClick={async()=>{setBusy(true);setError('');try{const data=await previewAction<IntegralReport>('reports/integral',{method:'POST',body:JSON.stringify({attemptIds:Object.values(chosen).filter(Boolean),shared})});setCreating(false);setReport(data);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Guardar copia y ver informe</Button></div></Dialog>
 <Dialog open={!!report} title="Informe integral de orientación" onClose={()=>setReport(null)} wide>{report&&<article className="stack integral-document"><header><h2>{report.student.name}</h2><p>{new Date(report.createdAt).toLocaleString('es-EC')}</p><p className="small muted">Copia {report.id.slice(0,8)} · Reglas {report.engineVersion}</p><Button variant="secondary" icon={<Download size={17}/>} onClick={()=>downloadIntegralReport(report)}>Descargar informe integral PDF</Button></header>{report.sections.map((section,i)=><section key={i}><h3>{section.title}</h3>{section.lines.map((line,j)=><p key={j}>{line}</p>)}</section>)}</article>}</Dialog></>;
}
