import {useState} from 'react';
import {Card} from '../../components/ui/primitives';
export function ReportContext({report}:{report:any}){
 const interest=report.instruments.find((s:any)=>s.instrumentId==='intereses');
 const scores=(interest?.scores||[]).map((s:any)=>s.raw as number),difference=scores.length?Math.max(...scores)-Math.min(...scores):0;
 const questions=report.instruments.reduce((n:number,s:any)=>n+s.instrument.questions.filter((q:any)=>s.answers[q.id]!==undefined).length,0);
 return <><div className="report-indicators"><Card><span>Tests entregados</span><strong>{report.instruments.length}</strong><small>Versiones guardadas en este reporte</small></Card><Card><span>Respuestas guardadas</span><strong>{questions}</strong><small>Respuestas presentes en las entregas</small></Card><Card><span>Diferencia entre intereses</span><strong>{interest?difference:'—'} <small>{interest?'/ 20':''}</small></strong><small>{!interest?'Completa el test de intereses':difference===0?'Todas las dimensiones están empatadas':'Distancia entre la mayor y menor suma RIASEC'}</small></Card></div><details className="report-method"><summary>Cómo leer estos resultados</summary><p>RIASEC resume intereses declarados en seis dimensiones. Cada suma va de 5 a 25. Autoconocimiento expresa la frecuencia indicada en las respuestas, transformada a una escala de 20 a 100: no es un porcentaje de aptitud ni una probabilidad de éxito.</p><p>El marco RIASEC cuenta con investigación publicada, pero eso no valida automáticamente las preguntas locales de esta plataforma. No se dispone de un estudio de validez, baremos o capacidad predictiva de estos cuestionarios para Ecuador. Las recomendaciones son hipótesis para contrastar con experiencias, mallas curriculares y acompañamiento humano.</p><a href="https://www.onetcenter.org/IP.html" target="_blank" rel="noreferrer">Consultar el marco de exploración de intereses de O*NET</a></details></>;
}
export function CareerOfferList({offers=[]}:{offers?:any[]}){
 const [query,setQuery]=useState('');const filtered=offers.filter(o=>(o.institution+' '+o.location+' '+o.modality).toLocaleLowerCase('es').includes(query.toLocaleLowerCase('es')));
 return <section className="career-offers"><h3>Dónde consultar esta carrera</h3><label className="field">Filtrar por institución, ciudad o modalidad<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label><p className="small muted">{filtered.length} ofertas en la consulta guardada. Su presencia no confirma cupos, admisión abierta ni acreditación actual.</p>{filtered.slice(0,12).map(o=><div className="career-offer" key={o.id}><b>{o.institution}</b><span>{o.title}</span><small>{o.location} · {o.modality} · {o.funding}</small></div>)}{filtered.length>12&&<p className="small muted">Afina la búsqueda para ver más instituciones.</p>}<a href="https://appcmi.ces.gob.ec/oferta_vigente/" target="_blank" rel="noreferrer">Verificar oferta vigente en el CES ↗</a></section>;
}
export function CatalogContext({report}:{report:any}){
 const [query,setQuery]=useState('');const source=report.catalogSource;if(!source)return null;
 const filtered=report.catalog.filter((c:any)=>c.name.toLocaleLowerCase('es').includes(query.toLocaleLowerCase('es')));
 return <details className="report-method"><summary>Oferta de Ecuador y alcance del catálogo</summary><p>{source.careerCount} denominaciones y {source.offerCount} ofertas de tercer nivel técnico, tecnológico y de grado. Consulta del {source.date}; no incluye posgrados ni garantiza que la oferta siga abierta.</p><label className="field">Buscar una carrera en el catálogo consultado<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ej. enfermería, software, agricultura"/></label>{query&&<><p className="small muted">{filtered.length} coincidencias</p><ul>{filtered.slice(0,20).map((c:any)=><li key={c.id}>{c.name}</li>)}</ul></>}<a href={source.sourceUrl} target="_blank" rel="noreferrer">Consultar fuente oficial: {source.source}</a></details>;
}
