import {useState} from 'react';
import type {Instrument} from '../../types';
import {Button,Card,Field,Notice,SelectField} from '../../components/ui/primitives';
import {previewAction,refreshSession} from '../../lib/session';
import {answerText} from '../../lib/test-answer-text';
import {ReleaseResult} from '../admin/ReleaseResult';
export function TestResult({submission:s,admin=false}:{submission:any;admin?:boolean}){
 const t:Instrument=JSON.parse(s.snapshot),answers=JSON.parse(s.answers),r=s.evaluation;
 const[pdf,setPdf]=useState(false),[reviews,setReviews]=useState<Record<string,Record<string,string>>>({}),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const label=(id:string)=>t.dimensions?.find(d=>d.id===id)?.name||id;
 if(!r)return null;
 return <Card className="stack test-result"><header><span className="eyebrow">RESULTADO DEL TEST</span><h2>{t.title}</h2><p className="small muted">Versión {s.version} · {new Date(s.created_at).toLocaleDateString('es-EC')} · Revisión {r.revision}</p></header><Notice tone={r.state==='complete'?'success':'warning'}>{r.state==='pending-review'?'Pendiente de revisión de la rúbrica':r.state==='insufficient'?'No hay cobertura suficiente para una interpretación final':'Resultado guardado'} · {r.coverage.responded} de {r.coverage.applicable} respuestas aplicables</Notice>
 {r.scores.map((score:any)=><section className="test-score" key={score.dimension}><div><h3>{label(score.dimension)}</h3><strong>{score.value.toLocaleString('es-EC',{maximumFractionDigits:2})}</strong></div><p className="small muted">Recorrido aplicable: {score.min} a {score.max} · {r.aggregation==='mean'?'Media ponderada':'Suma ponderada'}</p>{score.max>score.min&&<meter min={score.min} max={score.max} value={score.value} aria-label={label(score.dimension)}/>} {score.normalized!==undefined&&<p>Posición en el recorrido: {score.normalized.toFixed(2)} / 100</p>}{score.band&&<p>{score.band}</p>}</section>)}
 {!r.scores.length&&<p>{r.state==='pending-review'?'Las respuestas pendientes no reciben una puntuación de cero.':'Este instrumento conserva respuestas descriptivas, sin puntuación numérica.'}</p>}
 <p className="small muted">Estas puntuaciones describen este instrumento. Las respuestas omitidas y ocultas se excluyen del cálculo y del recorrido; no compares resultados con bases diferentes. No son porcentajes de aptitud. {!t.careerLinks?.length?'No se han configurado relaciones específicas con carreras para este test.':''}</p>
 {r.careers?.length>0&&<section className="stack"><h3>Carreras para explorar</h3>{r.careers.map((c:any)=><div className="preview-question" key={c.id}><h3>{c.careerName}</h3><p>{c.reason}</p><p className="small">Evidencia: {label(c.dimensionId)} = {c.evidence}. Criterio: {c.min} a {c.max}.</p><p className="small muted">Fuente del criterio: {c.source}</p><details><summary>Ofertas del catálogo consultado</summary>{c.offers?.map((o:any,i:number)=><p key={i}><b>{o.institution}</b><br/>{o.title} · {o.location} · {o.modality}</p>)}<a href={c.sourceUrl} target="_blank" rel="noreferrer">Consultar fuente oficial</a></details></div>)}</section>}
 <details><summary>Consultar respuestas</summary><div className="stack-sm">{t.questions.filter(q=>r.trace.some((x:any)=>x.questionId===q.id)).map(q=><div className="preview-question" key={q.id}><b>{q.text}</b><p>{answerText(t,q,answers[q.id])}</p></div>)}</div></details>
 {admin&&r.state==='pending-review'&&<form className="stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await previewAction('admin/tests/review',{method:'POST',body:JSON.stringify({id:s.id,reviews,reason})});await refreshSession();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><h3>Revisar rúbrica</h3>{t.questions.filter(q=>r.trace.some((x:any)=>x.questionId===q.id&&x.state==='pending-review')).map(q=><fieldset className="preview-question stack" key={q.id}><legend>{q.text}</legend><p>{answerText(t,q,answers[q.id])}</p>{q.rubric?.map(c=><SelectField key={c.id} label={c.label} required value={reviews[q.id]?.[c.id]||''} onChange={e=>setReviews({...reviews,[q.id]:{...reviews[q.id],[c.id]:e.target.value}})}><option value="">Selecciona un nivel</option>{c.levels.map(l=><option key={l.id} value={l.id}>{l.label} · {l.points} puntos</option>)}</SelectField>)}</fieldset>)}<Field label="Observación de la revisión" required value={reason} onChange={e=>setReason(e.target.value)}/>{error&&<Notice tone="danger">{error}</Notice>}<Button type="submit" loading={busy}>Guardar evaluación de la rúbrica</Button></form>}
 {admin&&<details><summary>Reglas aplicadas · motor {r.engineVersion}</summary>{r.trace.map((x:any,i:number)=><p className="small" key={i}>{t.questions.find(q=>q.id===x.questionId)?.text}: {x.state||`${label(x.dimension)} · ${x.contribution} × ${x.weight} = ${x.subtotal}`}</p>)}</details>}
 {admin&&r.state!=='pending-review'&&s.resultReleased===false&&<ReleaseResult id={s.id} released={false} onReleased={()=>void refreshSession()}/>}
 {(admin||s.resultReleased!==false)&&<div className="row"><Button variant="secondary" onClick={()=>setPdf(!pdf)}>{pdf?'Cerrar vista previa':'Vista previa del PDF'}</Button><a className="button button--secondary" target="_blank" rel="noreferrer" href={'/api/assessments/pdf?id='+encodeURIComponent(s.id)}>Abrir PDF</a></div>}{pdf&&<iframe className="test-result-pdf" title={'Informe PDF de '+t.title} src={'/api/assessments/pdf?id='+encodeURIComponent(s.id)+'#view=FitH'}/>}
 </Card>;
}
