import {manageUser,adminAnalytics} from '@/lib/server/admin-management';
import {refreshAcademicContent} from '@/lib/server/academic-content.mjs';
import {updateProfile,changePassword,requestEmail,confirmEmail} from '@/lib/server/account';
import {ensureGuidance,listGuidance,readGuidance,analyzeGuidance,configured} from '@/lib/server/guidance';
import {battery,batteryForClient,batterySubmissions} from '@/lib/server/battery';
import { instruments } from '@/components/kit/data/instruments';
import { NextRequest,NextResponse,after } from 'next/server';
import { randomBytes,randomUUID } from 'node:crypto';
import { platformInstitution,publicUser,releaseResult,db,fail,hash,passwordHash,passwordMatches,currentUser,requireUser,createSession,closeSession,rateLimit,workspace,document,put,validateTest } from '@/lib/server/store';
import { saveDocument,submitAssessment,evaluateInstrument } from '@/lib/server/operations';
import { renameGroup } from '@/lib/server/groups';
import { createIntegralReport,listIntegralReports,readIntegralReport } from '@/lib/server/integral-reports';
export const runtime='nodejs';
async function handle(req:NextRequest,{params}:{params:Promise<{action:string[]}>}){try{const action=(await params).action.join('/');if(req.method!=='GET'){const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)fail('Origen no autorizado.',403);if(req.headers.get('sec-fetch-site')==='cross-site')fail('Origen no autorizado.',403);if(Number(req.headers.get('content-length')||0)>2000000)fail('Solicitud demasiado grande.',413);}
const body=req.method==='GET'?{}:await req.json();let result:any;
if(action==='session')result=workspace(await currentUser());
else if(action==='auth/register'&&req.method==='POST'){rateLimit('register:'+hash(req.headers.get('x-forwarded-for')||'local'));const {name,email,password,institution}=body;if(typeof name!=='string'||name.trim().length<3||typeof email!=='string'||!/^\S+@\S+\.\S+$/.test(email)||typeof password!=='string'||password.length<8||password.length>128)fail('Revisa nombre, correo y contraseña (mínimo 8 caracteres).');if(db.prepare('SELECT id FROM users WHERE email=?').get(email.toLowerCase()))fail('No se pudo crear la cuenta con este correo.');const org=platformInstitution();if(document('institution:'+org.id,'rv360:admin-settings',{}).selfRegistration==='no')fail('El registro está cerrado temporalmente. Contacta con soporte.');const id=randomUUID();db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,?,?)').run(id,name.trim(),email.toLowerCase(),passwordHash(password),'student',org?.id||null,'','Activo');put(id,'rv360:profile',{name:name.trim(),email:email.toLowerCase(),stage:typeof body.stage==='string'?body.stage:'',institution:'',reminders:'no'});await createSession(id);result=workspace(await currentUser());}
else if(action==='auth/login'&&req.method==='POST'){if(typeof body.email!=='string'||typeof body.password!=='string'||body.password.length>128)fail('Credenciales no válidas.',401);rateLimit('login:'+hash(body.email.toLowerCase()));const row=db.prepare('SELECT * FROM users WHERE email=?').get(body.email.toLowerCase()) as any;const verified=passwordMatches(body.password,row?.password||passwordHash('invalid-password'));if(!row||!verified||row.status!=='Activo'||(body.admin?row.role==='student':row.role!=='student'))fail('Correo o contraseña incorrectos para este acceso.',401);await createSession(row.id);result=workspace(await currentUser());}
else if(action==='auth/logout'&&req.method==='POST'){await closeSession();result={ok:true};}
else if(action==='auth/password-reset'&&req.method==='POST'){if(!process.env.SMTP_HOST||!process.env.APP_URL)fail('El envío de correos aún no está configurado. Contacta con soporte para recuperar el acceso.',503);rateLimit('reset:'+hash(String(body.email)));const row=db.prepare('SELECT id,email FROM users WHERE email=?').get(String(body.email).toLowerCase()) as any;if(row){const token=randomBytes(32).toString('hex');db.prepare('INSERT INTO resets VALUES(?,?,?)').run(hash(token),row.id,Date.now()+1800000);const nodemailer=await import('nodemailer');const mail=nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:process.env.SMTP_SECURE==='true',auth:process.env.SMTP_USER?{user:process.env.SMTP_USER,pass:process.env.SMTP_PASSWORD}:undefined});await mail.sendMail({from:process.env.SMTP_FROM,to:row.email,subject:'Recupera tu acceso a Ruta Vocacional 360°',text:'Restablece tu contraseña en '+process.env.APP_URL+'/restablecer?token='+token+'\nEl enlace vence en 30 minutos.'});}result={ok:true};}
else if(action==='auth/reset-confirm'&&req.method==='POST'){if(typeof body.password!=='string'||body.password.length<8||body.password.length>128)fail('Usa una contraseña de 8 a 128 caracteres.');const reset=db.prepare('SELECT * FROM resets WHERE token=? AND expires>?').get(hash(String(body.token)),Date.now()) as any;if(!reset)fail('El enlace no es válido o ha vencido.');db.prepare('UPDATE users SET password=?,status=? WHERE id=?').run(passwordHash(body.password),'Activo',reset.userId);db.prepare('DELETE FROM resets WHERE userId=?').run(reset.userId);db.prepare('DELETE FROM sessions WHERE userId=?').run(reset.userId);const account=db.prepare('SELECT role FROM users WHERE id=?').get(reset.userId) as any;result={ok:true,loginPath:account.role==='student'?'/ingresar':'/admin/login'};}
else if(action==='account/adult'&&req.method==='POST'){fail('Este formulario ya no está disponible. Continúa en tu espacio.',410);}
else {const user=await requireUser();if(action==='state'&&req.method==='PUT'){const revision=saveDocument(user,body.key,body.value,body.revision);result={revision};}
else if(action==='admin/users'&&req.method==='POST')result=manageUser(user,body);
else if(action==='admin/analytics'&&req.method==='GET')result=adminAnalytics(user);
else if(action==='admin/orientation-content'&&req.method==='POST'){await requireUser(true);try{const shared=await refreshAcademicContent();result={source:shared.source,model:shared.model,contentId:shared.id,reused:!!shared.reused};}catch(e:any){fail(e.message==='PROVIDER_QUOTA'?'Cuota de Gemini agotada. Se conserva el contenido disponible.':e.message==='LOCAL_DAILY_LIMIT'?'Límite diario local alcanzado.':'No se pudo actualizar el contenido académico: '+e.message,e.message==='PROVIDER_QUOTA'||e.message==='LOCAL_DAILY_LIMIT'?429:502);}}
else if(action==='admin/tests/preview'&&req.method==='POST'){await requireUser(true);validateTest({...body.instrument,status:'Borrador'});if(!body.answers||typeof body.answers!=='object'||Array.isArray(body.answers))fail('Respuestas de prueba no válidas.');result={scores:evaluateInstrument(body.instrument,body.answers),engineVersion:'1',persisted:false};}
else if(action==='account/profile'&&req.method==='PUT')result=updateProfile(user,body);
else if(action==='account/password'&&req.method==='POST')result=await changePassword(user,body);
else if(action==='account/email'&&req.method==='POST')result=await requestEmail(user,body);
else if(action==='account/email/confirm'&&req.method==='POST')result=await confirmEmail(user,body);
else if(action==='battery/start'&&req.method==='POST'){battery(user,true);result=batteryForClient(user);}
else if(action==='reports/guidance'&&req.method==='GET'){if(user.role==='student'){try{ensureGuidance(user);}catch(e:any){if(e.status!==409)throw e;}}result={items:listGuidance(user),configured:configured()};}
else if(action==='reports/guidance/detail'&&req.method==='GET')result=readGuidance(user,req.nextUrl.searchParams.get('id')||'');
else if(action==='reports/guidance'&&req.method==='POST')result=await analyzeGuidance(user,body);
else if(action==='assessments/submit'&&req.method==='POST'){result=submitAssessment(user,body.instrumentId);{try{ensureGuidance(user);}catch(e:any){if(e.status!==409)throw e;}}}

else if(action==='reports/integral'&&req.method==='POST')fail('La generación de informes anteriores fue retirada. Consulta Mis resultados.',410);
else if(action==='reports/integral'&&req.method==='GET')result={items:listIntegralReports(user,req.nextUrl.searchParams.get('studentId'))};
else if(action==='reports/integral/detail'&&req.method==='GET')result=readIntegralReport(user,req.nextUrl.searchParams.get('id')||'');
else if(action==='admin/groups/rename'&&req.method==='POST')fail('La gestión de grupos fue retirada.',410);
else if(action==='admin/results/release'&&req.method==='POST'){result=releaseResult(user,body.id);const student=db.prepare('SELECT u.* FROM users u JOIN submissions s ON s.user_id=u.id WHERE s.id=?').get(String(body.id));if(student)ensureGuidance(publicUser(student));}
else if(action==='assessments/history')result={items:workspace(user).values['rv360:submissions']};
else if(action==='me/export')result={...workspace(user),guidanceReports:listGuidance(user),integralReports:listIntegralReports(user).map(report=>readIntegralReport(user,report.id))};
else if(action==='admin/audit'){await requireUser(true);result={items:document('institution:'+user.institutionId,'rv360:audit',[])};}
else if(action==='admin/versions'){await requireUser(true);const owner='institution:'+user.institutionId;let items=document(owner,'rv360:versions',[]);if(req.method==='POST'){const id=randomUUID();const content=document(owner,body.kind==='instrument'?'rv360:admin-draft:'+body.itemId:'rv360:admin-content',{});items=[{id,kind:body.kind,item_id:body.itemId,version:items.filter((v:any)=>v.item_id===body.itemId).length+1,status:'En revisión',content,created_at:new Date().toISOString()},...items];put(owner,'rv360:versions',items);result={id};}else if(req.method==='PATCH'){if(!['Publicado','Archivado','En revisión','Revisado'].includes(body.status))fail('Estado no válido.');const version=items.find((v:any)=>v.id===body.id);if(!version)fail('Versión no encontrada.',404);if(version.status==='Publicado'&&body.status==='En revisión')fail('La versión publicada es inmutable.');if(version.kind==='instrument'&&body.status==='Publicado'){const original=instruments.find(i=>i.id===version.item_id);if(!original)fail('Instrumento no encontrado.');const draft=version.content||{};const test={...original,id:'revision-'+version.id,version:String(version.version),status:'Publicado',publishedAt:new Date().toISOString(),group:'Todos los estudiantes',due:'',questions:[...original.questions.map(q=>({...q,text:draft[q.id]||q.text,dimension:draft[q.id+':dimension']||q.dimension})),...Object.keys(draft).filter(k=>k.startsWith('NEW-')&&!k.endsWith(':dimension')).map(id=>({id,text:draft[id],dimension:draft[id+':dimension']}))]};put(owner,'rv360:custom-tests',[...document(owner,'rv360:custom-tests',[]).filter((t:any)=>t.id!==test.id),test]);}if(version.kind==='instrument'&&body.status==='Archivado')put(owner,'rv360:custom-tests',document(owner,'rv360:custom-tests',[]).map((t:any)=>t.id==='revision-'+version.id?{...t,status:'Archivado'}:t));if(version.kind==='content'){const rows=document(owner,'rv360:published-content',[]).filter((r:any)=>r.versionId!==version.id);const content=Array.isArray(version.content)?version.content.find((c:any)=>c.id===version.item_id):null;if(body.status==='Publicado'&&content)rows.push({versionId:version.id,content:JSON.stringify(content)});put(owner,'rv360:published-content',rows);}put(owner,'rv360:audit',[{name:user.name,action:body.status,entity:version.item_id,created_at:new Date().toISOString()},...document(owner,'rv360:audit',[])]);items=items.map((v:any)=>v.id===body.id?{...v,status:body.status}:v);put(owner,'rv360:versions',items);result={ok:true};}else result={items};}
else fail('Operación no encontrada.',404);}
return NextResponse.json(result,{headers:{'Cache-Control':'no-store'}});
}catch(error:any){return NextResponse.json({error:error.status?error.message:'No se pudo completar la operación. Revisa los datos o el registro del servidor.'},{status:error.status||500});}}
export const GET=handle;export const POST=handle;export const PUT=handle;export const PATCH=handle;
