import {useEffect,useId,useMemo,useRef,useState,type ReactNode} from 'react';
import {Check,ChevronDown,Search} from 'lucide-react';
export type SearchOption={value:string;label:string;detail?:string};
export const normalized=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
export function SearchSelect({label,value,options,onChange,disabled=false,hint,icon}:{label:string;value:string;options:SearchOption[];onChange:(value:string)=>void;disabled?:boolean;hint?:string;icon?:ReactNode}){
 const id=useId(),root=useRef<HTMLDivElement>(null),input=useRef<HTMLInputElement>(null),[open,setOpen]=useState(false),[query,setQuery]=useState(''),[active,setActive]=useState(0);
 const indexed=useMemo(()=>options.map(o=>({...o,search:normalized(o.label+' '+(o.detail||''))})),[options]);
 const selected=options.find(o=>o.value===value),words=normalized(query).split(/\s+/),matches=indexed.filter(o=>words.every(w=>o.search.includes(w))),shown=matches.slice(0,60);
 useEffect(()=>{function outside(e:PointerEvent){if(!root.current?.contains(e.target as Node))setOpen(false);}document.addEventListener('pointerdown',outside);return()=>document.removeEventListener('pointerdown',outside);},[]);
 useEffect(()=>{root.current?.querySelector('[data-active="true"]')?.scrollIntoView({block:'nearest'});},[active]);
 function select(option:SearchOption){onChange(option.value);setOpen(false);setQuery('');input.current?.focus();}
 return <div ref={root} className="field search-select" onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setOpen(false);}}><label htmlFor={id}>{icon}{label}</label><div className="search-select-control"><Search size={17} aria-hidden="true"/><input ref={input} id={id} role="combobox" aria-expanded={open} aria-autocomplete="list" aria-controls={id+'-list'} aria-activedescendant={open&&shown[active]?id+'-'+active:undefined} aria-describedby={hint?id+'-hint':undefined} autoComplete="off" disabled={disabled} placeholder={disabled?'Selecciona primero la ubicación':'Busca o selecciona'} value={open?query:selected?.label||''} onFocus={()=>{setOpen(true);setQuery('');setActive(0);}} onClick={()=>setOpen(true)} onChange={e=>{setQuery(e.target.value);setActive(0);setOpen(true);}} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);e.preventDefault();}else if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();setOpen(true);setActive(i=>Math.max(0,Math.min(shown.length-1,i+(e.key==='ArrowDown'?1:-1))));}else if(e.key==='Enter'&&open){e.preventDefault();if(shown[active])select(shown[active]);}}}/><ChevronDown size={16} aria-hidden="true"/></div>{open&&!disabled&&<div className="search-select-popup"><div role="listbox" id={id+'-list'} aria-label={label}>{shown.map((o,i)=><button type="button" role="option" aria-selected={value===o.value} data-active={active===i} id={id+'-'+i} key={o.value} tabIndex={-1} onMouseDown={e=>e.preventDefault()} onClick={()=>select(o)}><span>{o.label}{o.detail&&<small>{o.detail}</small>}</span>{value===o.value&&<Check size={16}/>}</button>)}</div><p role="status">{!shown.length?'Sin coincidencias. Prueba otro nombre.':matches.length>60?'Mostrando 60 coincidencias. Escribe para precisar tu búsqueda.':`${matches.length} opciones`}</p></div>}{hint&&<small id={id+'-hint'} className="muted">{hint}</small>}</div>;
}
