import {useEffect,useMemo,useState} from 'react';
import {GraduationCap,MapPin,School} from 'lucide-react';
import type {EducationCatalog,EducationData} from '../../../../lib/education-types';
import {SearchSelect} from '../ui/SearchSelect';
import {Field,Checkbox} from '../ui/primitives';
import './education-fields.css';
import {BaccalaureateFields} from './BaccalaureateFields';
export type {EducationData} from '../../../../lib/education-types';
export const emptyEducation:EducationData={province:'',canton:'',parish:'',schoolId:'',institution:'',baccalaureate:'por-definir',specialty:'',learningPreference:'por-definir'};
const sort=(a:{label:string},b:{label:string})=>a.label.localeCompare(b.label,'es');
let cached:EducationCatalog|null=null;
export function EducationFields({value,onChange}:{value:EducationData;onChange:(v:EducationData)=>void}){
 return <div className="stack"><BaccalaureateFields value={value} onChange={onChange}/><SchoolFields value={value} onChange={onChange}/></div>;
}
function SchoolFields({value,onChange}:{value:EducationData;onChange:(v:EducationData)=>void}){
 const [catalog,setCatalog]=useState(cached),[loadError,setLoadError]=useState(false),[retry,setRetry]=useState(0),[onlyBach,setOnlyBach]=useState(true),[manual,setManual]=useState(!!value.institution&&!value.schoolId);
 useEffect(()=>{if(cached){setCatalog(cached);return;}let cancelled=false;setLoadError(false);fetch('/data/education-catalog.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(data=>{cached=data;if(!cancelled)setCatalog(data);}).catch(()=>{if(!cancelled)setLoadError(true);});return()=>{cancelled=true;};},[retry]);
 const province=catalog?.provinces.find(p=>p.id===value.province),canton=province?.cantons.find(c=>c.id===value.canton);
 const locations=useMemo(()=>new Map(catalog?.provinces.flatMap(p=>p.cantons.flatMap(c=>c.parishes.map(r=>[r.id,p.name+' · '+c.name+' · '+r.name] as const)))||[]),[catalog]);
 const options=useMemo(()=>catalog?.schools.filter(s=>(!onlyBach||s.baccalaureate||s.id===value.schoolId)&&(!value.province||s.province===value.province)&&(!value.canton||s.canton===value.canton)&&(!value.parish||s.parish===value.parish)).map(s=>({value:s.id,label:s.name,detail:locations.get(s.parish)+' · AMIE '+s.id}))||[],[catalog,onlyBach,value.schoolId,value.province,value.canton,value.parish,locations]);
 function school(id:string){const s=catalog?.schools.find(s=>s.id===id);if(s)onChange({...value,schoolId:id,institution:s.name,province:s.province,canton:s.canton,parish:s.parish});}
 const reset=(change:Partial<EducationData>)=>onChange({...value,schoolId:'',institution:manual?value.institution:'',...change});
 return <fieldset className="education-fields"><legend><GraduationCap size={19}/>Tu colegio de procedencia</legend><p className="education-intro">Busca por nombre o AMIE, o filtra por ubicación. Al elegir tu colegio completamos su ubicación.</p>{loadError?<p role="alert">No se pudo cargar el catálogo. <button type="button" className="text-link" onClick={()=>setRetry(v=>v+1)}>Reintentar</button> o escribe el nombre de tu colegio.</p>:!catalog?<p role="status">Cargando colegios…</p>:null}<details className="education-location"><summary><MapPin size={16}/>Ubicación y filtros{province&&<small>{province.name}{canton?" · "+canton.name:""}</small>}</summary><div className="education-grid"><SearchSelect label="Provincia del colegio" icon={<MapPin size={15}/>} value={value.province} disabled={!catalog} options={(catalog?.provinces||[]).map(p=>({value:p.id,label:p.name})).sort(sort)} onChange={province=>reset({province,canton:'',parish:''})}/><SearchSelect label="Cantón" value={value.canton} disabled={!province} options={(province?.cantons||[]).map(c=>({value:c.id,label:c.name})).sort(sort)} onChange={canton=>reset({canton,parish:''})}/><SearchSelect label="Parroquia" value={value.parish} disabled={!canton} options={(canton?.parishes||[]).map(p=>({value:p.id,label:p.name})).sort(sort)} onChange={parish=>reset({parish})}/><button type="button" className="education-manual" onClick={()=>reset({province:'',canton:'',parish:''})}>Limpiar ubicación</button></div></details>{manual?<Field label="Nombre del colegio" value={value.institution} maxLength={180} placeholder="Escribe el nombre completo" onChange={e=>onChange({...value,institution:e.target.value,schoolId:''})}/>:<><SearchSelect label="Colegio en el que te graduaste o estudias" icon={<School size={15}/>} value={value.schoolId} options={options} disabled={!catalog} onChange={school}/><Checkbox label="Mostrar solo instituciones con bachillerato" checked={onlyBach} onChange={e=>setOnlyBach(e.target.checked)}/></>}<button type="button" className="education-manual" onClick={()=>{setManual(!manual);onChange({...value,schoolId:'',institution:''});}}>{manual?'Volver al buscador de colegios':'No encuentro mi colegio · Escribir su nombre'}</button><p className="education-source">Fuente: MinEdec · 2025–2026 Inicio. Datos opcionales.</p></fieldset>;
}
