import {useState} from 'react';
import {useSession,flush} from '../../lib/session';
import {Button,SelectField,Notice} from '../ui/primitives';
import {Dialog} from '../ui/Dialog';
import './local-testing.css';
export function LocalTesting({admin=false,toolbar=false}:{admin?:boolean;toolbar?:boolean}){
 const session=useSession(),[open,setOpen]=useState(false),[id,setId]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[destination,setDestination]=useState('/mi-ruta/');
 if(process.env.NEXT_PUBLIC_DESIGN_PREVIEW!=='true')return null;
 const students=(session.values['rv360:admin-users']||[]).filter((u:any)=>u.role==='Estudiante'&&u.status==='Activo');
 async function change(returning=false){setBusy(true);setError('');try{await flush();const {designRequest}=await import('../../lib/design-preview');const result=await designRequest(returning?'local/return-admin':'admin/test-as-student',{method:'POST',body:JSON.stringify({id:id||students[0]?.id,returnPath:window.location.pathname})});window.location.assign(returning?result.returnPath||'/admin/evaluaciones/':destination);}catch(e){setError((e as Error).message);setBusy(false);}}
 if(!admin)return session.values['rv360:testing-as']?<aside className="local-testing-return"><span>Panel de {session.user?.name}</span><Button size="sm" variant="secondary" loading={busy} onClick={()=>void change(true)}>Volver a administración</Button>{error&&<Notice tone="danger">{error}</Notice>}</aside>:null;
 const trigger=<Button size="sm" variant="secondary" onClick={()=>{setOpen(true);setError('');}}>Probar como estudiante</Button>;
 return <>{toolbar?<aside className="local-testing-return"><span>Panel de administración · Contenido compartido en este navegador</span>{trigger}</aside>:trigger}<Dialog open={open} title="Comprobar la publicación" onClose={()=>{if(!busy)setOpen(false);}}><div className="stack"><p>Abre el panel de un estudiante de este navegador. El inicio y Mis tests mostrarán sus evaluaciones publicadas. En Cursos aparecerán los simuladores de sus carreras recomendadas. Sus respuestas y avances se guardarán en su cuenta.</p>{students.length?<><SelectField label="Estudiante para la prueba" value={id||students[0].id} onChange={e=>setId(e.target.value)}>{students.map((u:any)=><option value={u.id} key={u.id}>{u.name} · {u.email}</option>)}</SelectField><SelectField label="Apartado del estudiante" value={destination} onChange={e=>setDestination(e.target.value)}><option value="/mi-ruta/">Inicio del estudiante</option><option value="/mi-ruta/evaluaciones/">Mis tests</option><option value="/mi-ruta/cursos/">Autopreparación y simuladores</option></SelectField><p className="small muted">Puedes volver a administración desde el botón superior del panel.</p><Button loading={busy} onClick={()=>void change()}>Abrir panel del estudiante</Button></>:<><Notice>Crea primero una cuenta de estudiante en Usuarios, con su correo y contraseña. Después podrás probarla aquí.</Notice><a className="button button--secondary" href="/admin/usuarios/">Ir a Usuarios</a></>}{error&&<Notice tone="danger">{error}</Notice>}</div></Dialog></>;
}
