import {useState} from 'react';
import {Button,Notice} from '../ui/primitives';
import {refreshSession} from '../../lib/session';
import {downloadText} from '../../lib/storage';
export function TestPublication({admin=false}:{admin?:boolean}){
 const [packet,setPacket]=useState<any>(null),[error,setError]=useState(''),[message,setMessage]=useState('');
 if(process.env.NEXT_PUBLIC_DESIGN_PREVIEW!=='true')return null;
 return <details className="report-method"><summary>{admin?'Publicar tests en otro perfil o equipo':'Cargar tests publicados por administración'}</summary><p>Los tests se comparten automáticamente entre pestañas del mismo perfil. Para otro perfil o equipo, carga el archivo de publicación de administración.</p>{admin?<><p>Incluye únicamente tests publicados para todos los estudiantes. No incluye cuentas, contraseñas ni respuestas.</p><Button variant="secondary" onClick={async()=>{try{const {exportTestPublication}=await import('../../lib/test-publication');const p=exportTestPublication();downloadText('tests-publicados.rv360.json',JSON.stringify(p,null,2),'application/json');setMessage(p.tests.length+' tests incluidos en la publicación.');setError('');}catch(e){setError((e as Error).message);}}}>Descargar publicación</Button></>:<><label className="field">Archivo de publicación<input type="file" accept=".json" onChange={async e=>{setPacket(null);setError('');setMessage('');try{const f=e.target.files?.[0];if(!f)return;if(f.size>10*1024*1024)throw Error('El archivo supera 10 MB.');const {validateTestPublication}=await import('../../lib/test-publication');setPacket(validateTestPublication(JSON.parse(await f.text())));}catch(e){setError((e as Error).message);}}}/></label>{packet&&<div className="stack"><p>{packet.tests.length} tests · Publicación del {new Date(packet.createdAt).toLocaleString('es-EC')}</p><p>Actualiza los tests de este origen y conserva tus respuestas anteriores.</p><Button onClick={async()=>{try{const {importTestPublication}=await import('../../lib/test-publication');const count=importTestPublication(packet);await refreshSession();setMessage(count+' tests cargados. Ya puedes encontrarlos en Mis tests.');setPacket(null);setError('');}catch(e){setError((e as Error).message);}}}>Cargar publicación</Button></div>}</>}{error&&<Notice tone="danger">{error}</Notice>}{message&&<Notice tone="success">{message}</Notice>}</details>;
}
