import type {Instrument,Question} from '../../types';
import {Field,TextareaField} from '../ui/primitives';
export {answerText} from '../../lib/test-answer-text';
function QuestionInput({instrument:t,question:q,value,onChange}:{instrument:Instrument;question:Question;value:any;onChange:(value:any)=>void}){
 const options=q.options||t.options;
 const selections=(v:any,change:(n:any)=>void,multiple:boolean,name:string)=><div className="preview-options">{options.map(o=>{const checked=multiple?Array.isArray(v)&&v.includes(o.value):v===o.value;return <label key={o.id||o.value} className={checked?'selected':''}><input type={multiple?'checkbox':'radio'} name={name} checked={checked} onChange={()=>change(multiple?(checked?v.filter((n:number)=>n!==o.value):o.value===q.exclusiveValue?[o.value]:[...(Array.isArray(v)?v.filter(n=>n!==q.exclusiveValue):[]),o.value]):o.value)}/><span>{o.label}</span></label>;})}</div>;
 if(q.type==='info')return <p>{q.help||'Continúa cuando hayas leído esta información.'}</p>;
 if(q.type==='number')return <Field label={'Tu respuesta'+(q.unit?' ('+q.unit+')':'')} type="number" min={q.min} max={q.max} step={q.step||'any'} value={value??''} onChange={e=>onChange(e.target.value===''?'':Number(e.target.value))}/>;
 if(q.type==='short')return <Field label="Tu respuesta" maxLength={q.maxLength||10000} value={value||''} onChange={e=>onChange(e.target.value)}/>;
 if(q.type==='open')return <TextareaField label="Tu respuesta" rows={5} maxLength={q.maxLength||10000} value={value||''} onChange={e=>onChange(e.target.value)}/>;
 if(q.type==='matrix')return <div className="stack">{q.rows?.map(row=><fieldset className="preview-question" key={row.id}><legend>{row.label}</legend>{selections(value?.[row.id],v=>onChange({...value,[row.id]:v}),!!q.matrixMultiple,q.id+'-'+row.id)}</fieldset>)}</div>;
 if(q.type==='ranking'){const ordered:Array<number>=Array.isArray(value)?value:[];return <div className="stack-sm"><p className="small muted">Añade las opciones en el orden que prefieras. Después puedes moverlas.</p>{ordered.map((n,i)=><div className="ranking-row" key={n}><span>{i+1}. {options.find(o=>o.value===n)?.label}</span><button type="button" disabled={!i} aria-label={'Subir '+options.find(o=>o.value===n)?.label} onClick={()=>{const next=[...ordered];[next[i-1],next[i]]=[next[i],next[i-1]];onChange(next);}}>↑</button><button type="button" disabled={i===ordered.length-1} aria-label={'Bajar '+options.find(o=>o.value===n)?.label} onClick={()=>{const next=[...ordered];[next[i+1],next[i]]=[next[i],next[i+1]];onChange(next);}}>↓</button><button type="button" aria-label={'Quitar '+options.find(o=>o.value===n)?.label} onClick={()=>onChange(ordered.filter(v=>v!==n))}>×</button></div>)}{options.filter(o=>!ordered.includes(o.value)).map(o=><button type="button" className="button button--secondary" key={o.value} onClick={()=>onChange([...ordered,o.value])}>Añadir {o.label}</button>)}</div>;}
 return <>{q.type==='multiple'&&<p className="small muted">Selecciona entre {q.minSelections??1} y {q.maxSelections??options.length} opciones.</p>}{selections(value,onChange,q.type==='multiple',q.id)}</>;
}

export function TestQuestion(props:{instrument:Instrument;question:Question;value:any;onChange:(value:any)=>void}){return <div className="stack-sm">{props.question.section&&<p className="eyebrow">{props.question.section}</p>}{props.question.help&&props.question.type!=='info'&&<p className="muted small">{props.question.help}</p>}<QuestionInput {...props}/></div>;}
