import {useState,type ReactNode} from 'react';
import Link from 'next/link';
import {LayoutDashboard,Users,Building2,ClipboardList,ChartNoAxesCombined,Settings,LogOut,Menu,ShieldCheck} from 'lucide-react';
import {useSession,logout,flush} from '../../lib/session';
import {Dialog} from '../ui/Dialog';
import {Button} from '../ui/primitives';
import type {View} from '../../types';
import '../../features/admin/admin-design.css';
const entries=[['admin','/admin','Resumen',LayoutDashboard],['usuarios','/admin/usuarios','Usuarios',Users],['editor','/admin/evaluaciones','Evaluaciones',ClipboardList],['admin-resultados','/admin/resultados','Resultados e informes',ChartNoAxesCombined],['ajustes','/admin/configuracion','Configuración',Settings]] as const;
export function AdminShell({children,view}:{children:ReactNode;view:View}){const session=useSession(),[open,setOpen]=useState(false),[error,setError]=useState('');const links=entries.filter(([id])=>session.user?.role==='admin'||['admin','admin-resultados'].includes(id));const navigation=<nav aria-label="Administración">{links.map(([id,url,title,Icon])=><Link href={url} aria-current={view===id?'page':undefined} onClick={()=>setOpen(false)} key={id}><Icon size={19}/>{title}</Link>)}</nav>;
 return <div className="ad-app"><aside className="ad-sidebar"><Link className="ad-brand" href="/admin"><img src="/media/brain-book-icon.png" alt=""/><span>Ruta Vocacional <b>360°</b><small>ADMINISTRACIÓN</small></span></Link>{navigation}<div className="ad-side-bottom"><Link href="/admin/cuenta"><span className="ad-avatar">{session.user?.name.slice(0,2)}</span><span>{session.user?.name}<small>Mi cuenta y seguridad</small></span></Link><button onClick={async()=>{try{await flush();await logout();location.assign('/admin/login');}catch(e){setError((e as Error).message);}}}><LogOut size={17}/>Cerrar sesión</button>{error&&<p role="alert">{error}</p>}</div></aside><div className="ad-workspace"><header className="ad-topbar"><button className="ad-menu" aria-label="Abrir menú administrativo" onClick={()=>setOpen(true)}><Menu size={22}/></button><div><span>PLATAFORMA · ECUADOR</span><strong>{session.values['rv360:admin-settings']?.name||'Ruta Vocacional 360°'}</strong></div><Link href="/admin/cuenta"><ShieldCheck size={17}/><span>{session.user?.role==='admin'?'Administrador':'Orientador'}</span></Link></header><main id="contenido" className="ad-content" key={view}>{children}</main></div><Dialog open={open} title="Administración" onClose={()=>setOpen(false)}><div className="ad-mobile-nav">{navigation}<Link href="/admin/cuenta" onClick={()=>setOpen(false)}>Mi cuenta</Link><Button variant="ghost" onClick={async()=>{await flush();await logout();location.assign('/admin/login');}}>Cerrar sesión</Button></div></Dialog></div>;
}
